"""Score part -> band SoundFont preset: the reference resolver every player implements.

    uv run --project sounds python sounds/partsound.py "Tenor Horn" "Tuba" ...   # resolve names
    uv run --project sounds python sounds/partsound.py --vectors                 # rewrite partsound-vectors.json

The rules live in sounds/mapping.json `resolve` (normalize, then exact, alias, keyword,
instrument, GM program). sounds/partsound-vectors.json holds input -> expected preset rows that
the Apple, Android, Windows and Studio tests read, so the four resolvers cannot drift apart.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAPPING = HERE / "mapping.json"
VECTORS = HERE / "partsound-vectors.json"


def normalize(name: str) -> str:
    s = name.lower().replace("♭", "b").replace("♯", "#")
    return re.sub(r"\s+", " ", s.replace(" ", " ")).strip()


@dataclass(frozen=True)
class Preset:
    part: str  # the mapping.json part whose preset plays
    step: str  # exact | alias | keyword | instrument | program
    program: int
    bank: int
    channel_gain_db: float
    percussion: bool


def resolve(name: str, mapping: dict, instrument: str | None = None, program: int | None = None) -> Preset | None:
    parts = mapping["parts"]
    r = mapping["resolve"]
    n = normalize(name)
    hit, step = None, None
    by_norm = {normalize(k): k for k in parts}
    if n in by_norm:
        hit, step = by_norm[n], "exact"
    elif n in r["aliases"]:
        hit, step = r["aliases"][n], "alias"
    else:
        for kw, part in r["keywords"]:
            if kw in n:
                hit, step = part, "keyword"
                break
    if hit is None and instrument and instrument in r["instruments"]:
        hit, step = r["instruments"][instrument], "instrument"
    if hit is None and program is not None and str(program) in r["programs"]:
        hit, step = r["programs"][str(program)], "program"
    if hit is None:
        return None
    bs = parts[hit]["band_soundfont"]
    return Preset(hit, step, bs["program"], bs["bank"], bs["channel_gain_db"], bs["bank"] == 128)


VECTOR_INPUTS = [
    # every lineup part, by its exact name
    *[(None,)],
    # names other writers use
    ("1st Cornet",), ("Cornet 1",), ("Cornet",), ("Solo Cornet ",), ("Trumpet in B♭",), ("Tenor Horn",),
    ("Horn in E♭",), ("E♭ Horn",), ("Alto Horn",), ("Flugel",), ("Flügelhorn",), ("Baritone",), ("Baritone Horn",),
    ("Euphonium 2",), ("Trombone",), ("Bass Trombone",), ("Tuba",), ("Bass",), ("B♭ Tuba",), ("Eb Bass",), ("BBb Bass",),
    ("Drum Set",),
    # unknown names resolved by instrument or GM program
    ("Part 1", "brass.alto-horn", None), ("Part 2", "brass.euphonium", None), ("P3", None, 56), ("P4", None, 58),
    ("Piano", None, 0),
]


def vectors(mapping: dict) -> list[dict]:
    rows = []
    names = []
    for lineup, ps in mapping["lineups"].items():
        if lineup != "about":
            names += [p for p in ps if p not in names]
    inputs = [(p, None, None) for p in names] + [v if len(v) == 3 else (v[0], None, None) for v in VECTOR_INPUTS[1:]]
    seen = set()
    for name, inst, prog in inputs:
        if (name, inst, prog) in seen:
            continue
        seen.add((name, inst, prog))
        p = resolve(name, mapping, inst, prog)
        rows.append({"name": name, "instrument": inst, "program": prog,
                     "expect": None if p is None else {"part": p.part, "step": p.step, "program": p.program, "bank": p.bank,
                                                        "channel_gain_db": p.channel_gain_db, "percussion": p.percussion}})
    return rows


def main() -> None:
    mapping = json.loads(MAPPING.read_text())
    if sys.argv[1:] == ["--vectors"]:
        rows = vectors(mapping)
        VECTORS.write_text(json.dumps({"about": "Generated by sounds/partsound.py --vectors from sounds/mapping.json. "
                                                "Input (name, MusicXML instrument-sound or instrument id, 0-based GM program) "
                                                "-> the band SoundFont preset every player must pick. expect null: unresolved "
                                                "(not a brass-band instrument).", "vectors": rows},
                                      indent=1, ensure_ascii=False) + "\n")
        print(f"{VECTORS}: {len(rows)} vectors")
        return
    for name in sys.argv[1:]:
        print(name, "->", resolve(name, mapping))


if __name__ == "__main__":
    main()
