"""Build App/Localizable.xcstrings (English source, Norwegian bokmål) from the keys Xcode
extracted into *.stringsdata during the last build, plus the bokmål table below.

Usage: python3 scripts/make-string-catalog.py build/DerivedData/Build/Intermediates.noindex
Keys without a translation are listed on stderr and left for review in Xcode.
"""

import glob
import json
import sys

NB = {
    "%lld": "%lld",
    "%lld %%": "%lld %%",
    "%lld percent": "%lld prosent",
    "%lld uncertain notes": "%lld usikre noter",
    "A brass band playing together.": "Et brassband som spiller sammen.",
    "A single player, for example you practising.": "Én utøver, for eksempel deg når du øver.",
    "A soloist in front of an orchestra or band.": "En solist foran et orkester eller korps.",
    "About": "Om",
    "About %lld min left": "Omtrent %lld min igjen",
    "Address": "Adresse",
    "All parts": "Alle stemmer",
    "Arranging for brass band": "Arrangerer for brassband",
    "Audio of the score": "Lyd av partituret",
    "Back": "Tilbake",
    "Bar %lld, beat %lld": "Takt %lld, slag %lld",
    "Bars": "Takter",
    "Bars %lld–%lld: ad lib (free time)": "Takt %lld–%lld: ad lib (fritt tempo)",
    "Bars with uncertain notes": "Takter med usikre noter",
    "Baseline sounds: MuseScore General SoundFont (MIT), downloaded separately.": "Grunnlyder: MuseScore General SoundFont (MIT), lastes ned separat.",
    "Braille music (BRF)": "Punktskriftnoter (BRF)",
    "Brass band": "Brassband",
    "Brasscribe Play": "Brasscribe Play",
    "Cancel": "Avbryt",
    "Cancelled.": "Avbrutt.",
    "Check connection": "Sjekk tilkoblingen",
    "Concert": "Klingende",
    "Concert hall and seating": "Konsertsal og plassering",
    "Connected to Brasscribe %@ (%@).": "Koblet til Brasscribe %@ (%@).",
    "Couldn't open the score": "Kunne ikke åpne partituret",
    "Couldn't open this file.": "Kunne ikke åpne filen.",
    "Count-in": "Inntelling",
    "Count-in %lld": "Inntelling %lld",
    "Count-in: C · Metronome: M · Play along: A": "Inntelling: C · Metronom: M · Spill med: A",
    "Delete": "Slett",
    "Difficulty": "Vanskelighetsgrad",
    "Done": "Ferdig",
    "Double-tap to move playback here.": "Dobbelttrykk for å flytte avspillingen hit.",
    "Easier": "Enklere",
    "Engraving the score": "Setter partituret",
    "Engraving the score…": "Setter partituret …",
    "Estimating time…": "Beregner tid …",
    "Everything playing on this Mac": "All lyd som spilles på denne Macen",
    "Export": "Del eller skriv ut",
    "Faithful": "Tro mot opptaket",
    "Faster": "Raskere",
    "Finding the beat": "Finner pulsen",
    "Free time": "Fritt tempo",
    "Full brass band": "Fullt brassband",
    "Getting the recording ready": "Gjør opptaket klart",
    "Import audio or video": "Importer lyd eller video",
    "Input level": "Inngangsnivå",
    "Keep the original key": "Behold originaltonearten",
    "Key (concert)": "Toneart (klingende)",
    "Less than a minute left": "Under ett minutt igjen",
    "Lineup": "Besetning",
    "Lineup, difficulty and key are sent to your computer; older versions of Brasscribe may ignore them.": "Besetning, vanskelighetsgrad og toneart sendes til datamaskinen din. Eldre versjoner av Brasscribe kan overse dem.",
    "Links to streaming sites can't be downloaded. Play the music and record it, or import a file you have.": "Lenker til strømmetjenester kan ikke lastes ned. Spill av musikken og ta den opp, eller importer en fil du har.",
    "Listen to the original": "Hør originalen",
    "Listen to uncertain bars": "Hør på usikre takter",
    "Loop": "Gjenta",
    "Loop current bar: L": "Gjenta denne takten: L",
    "Loop from bar": "Gjenta fra takt",
    "Loop this bar": "Gjenta denne takten",
    "Loop to bar": "Gjenta til takt",
    "MIDI": "MIDI",
    "Making the audio": "Lager lyden",
    "Metronome": "Metronom",
    "Microphone access is off. Turn it on in Settings to record.": "Mikrofontilgang er slått av. Slå den på i Innstillinger for å ta opp.",
    "MusicXML (score and parts)": "MusicXML (partitur og stemmer)",
    "Mute": "Demp",
    "Mute %@": "Demp %@",
    "Mutes your part so you can play it.": "Skrur av stemmen din så du kan spille den selv.",
    "My part": "Min stemme",
    "New score": "Nytt partitur",
    "Next bar": "Neste takt",
    "Loop current bar": "Gjenta gjeldende takt",
    "Original or score": "Original eller partitur",
    "Play or pause": "Spill av eller pause",
    "Notation engraved with Verovio (LGPL-3.0), included as an unmodified dynamic framework.": "Notene settes med Verovio (LGPL-3.0), som følger med som et uendret dynamisk rammeverk.",
    "Nothing was heard. Either nothing was playing, recording permission was refused, or the app plays protected (DRM) audio, which the system does not let anyone record.": "Ingenting ble hørt. Enten ble ingenting spilt av, tillatelsen til opptak ble avslått, eller appen spiller beskyttet lyd (DRM), som systemet ikke lar noen ta opp.",
    "OK": "OK",
    "One instrument": "Ett instrument",
    "Only silence was recorded": "Bare stillhet ble tatt opp",
    "Open score": "Åpne partituret",
    "Orchestra or band with a soloist": "Orkester eller korps med solist",
    "Original": "Original",
    "Original / score: O": "Original / partitur: O",
    "Original recording": "Originalopptak",
    "PDF": "PDF",
    "Pair": "Koble til",
    "Paired.": "Tilkoblet.",
    "Pairing code": "Tilkoblingskode",
    "Part": "Stemme",
    "Parts": "Stemmer",
    "Parts and sound": "Stemmer og lyd",
    "Pause": "Pause",
    "Pitch": "Tonehøyde",
    "Play": "Spill av",
    "Play %@": "Spill %@",
    "Play along": "Spill med",
    "Play along (mute my part)": "Spill med (demp min stemme)",
    "Play or pause: Space": "Spill eller pause: mellomrom",
    "Play this bar": "Spill denne takten",
    "Play when you're ready.": "Spill når du er klar.",
    "Playback": "Avspilling",
    "Playback problem": "Problem med avspillingen",
    "Pop or rock": "Pop eller rock",
    "Previous / next bar: ← / →": "Forrige / neste takt: ← / →",
    "Previous bar": "Forrige takt",
    "Protected (DRM) music and video can't be recorded or imported. Play the piece yourself, or use a file you own without copy protection.": "Beskyttet musikk og video (DRM) kan ikke tas opp eller importeres. Spill stykket selv, eller bruk en fil du eier uten kopibeskyttelse.",
    "Protected (DRM) playback, as in some streaming apps, can't be recorded; you'll hear it but the recording stays silent.": "Beskyttet avspilling (DRM), som i noen strømmeapper, kan ikke tas opp. Du hører lyden, men opptaket blir stille.",
    "Record": "Ta opp",
    "Record from": "Ta opp fra",
    "Record sound playing on this Mac": "Ta opp lyd som spilles på denne Macen",
    "Record this Mac": "Ta opp fra denne Macen",
    "Record with the microphone": "Ta opp med mikrofonen",
    "Recorded": "Tatt opp",
    "Recorded %lld seconds": "%lld sekunder tatt opp",
    "Recording %@": "Opptak %@",
    "Recording…": "Tar opp …",
    "Review": "Gjennomgang",
    "Score": "Partitur",
    "Score pages": "Partitursider",
    "Scores": "Partiturer",
    "Sending the recording": "Sender opptaket",
    "Separating the instruments": "Skiller instrumentene fra hverandre",
    "Settings": "Innstillinger",
    "Show": "Vis",
    "Slower": "Saktere",
    "Slower / faster: [ / ]": "Saktere / raskere: [ / ]",
    "Small band": "Lite band",
    "Solo": "Solo",
    "Solo %@": "Solo %@",
    "Sound": "Lyd",
    "Sounds": "Lyder",
    "Speed": "Tempo",
    "Standard": "Standard",
    "Start Brasscribe on your computer with “brasscribe serve --host 0.0.0.0” and type the six-digit code it shows.": "Start Brasscribe på datamaskinen med «brasscribe serve --host 0.0.0.0» og skriv inn den sekssifrede koden som vises.",
    "Start recording": "Start opptak",
    "Stop": "Stopp",
    "Switch between the score and the original recording at the same place.": "Bytt mellom partituret og originalopptaket på samme sted.",
    "Talking score": "Talende partitur",
    "Talking score (text)": "Talende partitur (tekst)",
    "The notation engine could not start.": "Notesettingen kunne ikke starte.",
    "The performer did not keep a steady beat here, so rhythms are approximate.": "Utøveren holdt ikke jevn puls her, så rytmene er omtrentlige.",
    "This decides how the music is taken apart. Brasscribe never guesses.": "Dette avgjør hvordan musikken tas fra hverandre. Brasscribe gjetter aldri.",
    "This is not a score Brasscribe can read.": "Dette er ikke et partitur Brasscribe kan lese.",
    "This recording is copy-protected": "Dette opptaket er kopibeskyttet",
    "Transcribe": "Skriv ned tonene",
    "Transcribing on %@": "Skriver ned tonene på %@",
    "Transpose %@%lld semitones": "Transponer %@%lld halvtoner",
    "Uncertain notes": "Usikre noter",
    "Uncertain notes are marked with an open diamond and an orange colour.": "Usikre noter er merket med en åpen rute og oransje farge.",
    "Video of the performance, synced to the score": "Video av framføringen, synkronisert med partituret",
    "Vocals or lead with bass, drums and keys.": "Sang eller melodi med bass, trommer og tangenter.",
    "What is this?": "Hva er dette?",
    "Working": "Jobber",
    "Writing down the notes": "Skriver ned tonene",
    "Written": "Notert",
    "Your computer": "Datamaskinen din",
    "Your scores appear here.": "Partiturene dine vises her.",
    "Zoom %lld percent": "Zoom %lld prosent",
    "Zoom in": "Zoom inn",
    "%lld to download (%lld MB)": "%lld må lastes ned (%lld MB)",
    "Download models": "Last ned modellene",
    "Model download address": "Adresse for nedlasting av modeller",
    "Models": "Modeller",
    "Models ready.": "Modellene er klare.",
    "On this device": "På denne enheten",
    "Original key": "Originaltoneart",
    "Picture in picture": "Bilde i bilde",
    "Pitch and beat models (about 40 MB) are downloaded once and not included in the app.": "Modellene for tonehøyde og puls (omtrent 40 MB) lastes ned én gang og følger ikke med appen.",
    "Ready": "Klar",
    "Remove downloaded models": "Fjern nedlastede modeller",
    "Solos are transcribed on this device. Other recordings go to your computer.": "Soloer skrives ned på denne enheten. Andre opptak sendes til datamaskinen din.",
    "Stop picture in picture": "Stopp bilde i bilde",
    "Transcribe solos on this device": "Skriv ned soloer på denne enheten",
    "Your computer arranges the score with these choices.": "Datamaskinen din arrangerer partituret med disse valgene.",
    "available": "tilgjengelig",
    "this device": "denne enheten",
    "unavailable": "ikke tilgjengelig",
    "The small band is arranged on this device. Difficulty is noted but not applied yet.": "Lite band arrangeres på denne enheten. Vanskelighetsgraden blir notert, men ikke brukt ennå.",
    "Arrange again on this device": "Arranger på nytt på denne enheten",
    "Couldn't arrange on this device.": "Kunne ikke arrangere på denne enheten.",
    "Zoom out": "Zoom ut",
    "from %lld": "fra %lld",
    "to %lld": "til %lld",
    # the design-system restyle
    "%@ %@": "%@ %@",
    "%@ %@ %@": "%@ %@ %@",
    "%@ (concert)": "%@ (klingende)",
    "%@ didn't answer. Check that it's still open.": "%@ svarte ikke. Sjekk at Brasscribe fortsatt er åpent.",
    "%@ for B♭ · %@ for E♭ instruments": "%@ for B-instrumenter · %@ for Ess-instrumenter",
    "%@%@": "%@%@",
    "%@, %@": "%@, %@",
    "%@. Check them": "%@. Sjekk dem",
    "%lld MB to download": "%lld MB å laste ned",
    "%lld bars": "%lld takter",
    "%lld files": "%lld filer",
    "%lld notes in %@, %lld very unsure, first.": "%lld toner i %@, %lld svært usikre først.",
    "%lld notes in %@.": "%lld toner i %@.",
    "%lld notes keep their ? marks. You can check them any time from the score: tap “Check them”.": "%lld toner beholder ?-merket. Du kan sjekke dem når som helst fra partituret: trykk «Sjekk dem».",
    "%lld notes marked ?": "%lld toner merket ?",
    "%lld notes marked ? (boxed ? = very unsure)": "%lld toner merket ? (? i ramme = svært usikker)",
    "%lld of %lld · %@": "%lld av %lld · %@",
    "%lld semitones down": "%lld halvtoner ned",
    "%lld semitones up": "%lld halvtoner opp",
    "1 file": "1 fil",
    "1 note marked ?": "1 tone merket ?",
    "1 note marked ? (boxed ? = very unsure)": "1 tone merket ? (? i ramme = svært usikker)",
    "1 semitone down": "1 halvtone ned",
    "1 semitone up": "1 halvtone opp",
    "10–15 players, parts doubled up": "10–15 musikere, stemmene doblet",
    "? = Brasscribe wasn't sure. Boxed ? = very unsure. · Page %lld of %lld": "? = Brasscribe var usikker. ? i ramme = svært usikker. · Side %lld av %lld",
    "A bit easier": "Litt enklere",
    "A file you own, or a recording with the microphone, always works.": "En fil du eier, eller et opptak med mikrofonen, virker alltid.",
    "A note at the bottom of each page explains them": "En merknad nederst på hver side forklarer dem",
    "A whole band playing together, with no other instruments.": "Et helt korps som spiller sammen, uten andre instrumenter.",
    "About %lld minutes left": "Omtrent %lld minutter igjen",
    "About 1 minute left": "Omtrent 1 minutt igjen",
    "About 25 players": "Omtrent 25 musikere",
    "All parts (%lld)": "Alle stemmer (%lld)",
    "As": "Som",
    "As played": "Som spilt",
    "As recorded": "Som i opptaket",
    "As written": "Notert",
    "As written for %@": "Notert for %@",
    "Audio": "Lyd",
    "BRF file for a braille display or embosser": "BRF-fil for leselist eller punktskriver",
    "Back to Home": "Tilbake til Hjem",
    "Band or recording": "Band eller opptak",
    "Bar %lld": "Takt %lld",
    "Bar %lld has no steady beat (ad lib.). Its rhythms are approximate.": "Takt %lld har ingen fast puls (ad lib.). Rytmene der er omtrentlige.",
    "Bars %lld to %lld": "Takt %lld til %lld",
    "Bars %lld–%lld have no steady beat (ad lib.). Their rhythms are approximate.": "Takt %lld–%lld har ingen fast puls (ad lib.). Rytmene der er omtrentlige.",
    "Braille music": "Punktskriftnoter",
    "Brasscribe can't use it, for one of these reasons:": "Brasscribe kan ikke bruke den, av en av disse grunnene:",
    "Brasscribe couldn't make brass-band parts from this score.": "Brasscribe klarte ikke å lage stemmer for brassband fra dette partituret.",
    "Brasscribe on your computer": "Brasscribe på datamaskinen",
    "Brasscribe on your computer can't be reached. Check that it's open, and on the same network.": "Får ikke kontakt med Brasscribe på datamaskinen. Sjekk at det er åpent og på samme nettverk.",
    "Brasscribe opens MusicXML scores and its own score files.": "Brasscribe åpner MusicXML-partitur og sine egne partiturfiler.",
    "Brasscribe stopped before the notes were written down. Your recording is safe.": "Brasscribe stoppet før tonene var skrevet ned. Opptaket ditt er trygt.",
    "Brasscribe wasn't sure": "Brasscribe var usikker",
    "Change": "Endre",
    "Check the connection": "Sjekk tilkoblingen",
    "Check the marked notes": "Sjekk de merkede tonene",
    "Check them": "Sjekk dem",
    "Check your part first": "Sjekk stemmen din først",
    "Choose another file": "Velg en annen fil",
    "Choose one to continue.": "Velg én for å fortsette.",
    "Concert hall sound": "Konsertsallyd",
    "Concert pitch": "Klingende",
    "Conductor's score": "Dirigentpartitur",
    "Connected to Brasscribe %@ on %@.": "Koblet til Brasscribe %@ på %@.",
    "Continue": "Fortsett",
    "Details for the band's tech person": "Detaljer for den tekniske i bandet",
    "The band sounds are missing. Reinstall Brasscribe Play to hear the band.": "Lydene til bandet mangler. Installer Brasscribe Play på nytt for å høre bandet.",
    "Download address": "Nedlastingsadresse",
    "Download the listening files": "Last ned lyttefilene",
    "Drop a recording here": "Slipp et opptak her",
    "Easier keeps the tune but avoids high notes and fast runs.": "Enklere beholder melodien, men unngår høye toner og raske løp.",
    "Edit in MuseScore, Sibelius or Dorico": "Rediger i MuseScore, Sibelius eller Dorico",
    "Every part": "Alle stemmer",
    "Every part: one PDF per player.": "Alle stemmer: én PDF per musiker.",
    "For other music apps": "For andre musikkapper",
    "For printing and the music stand": "For utskrift og notestativet",
    "Found %@. Type the six digits it shows to pair.": "Fant %@. Skriv de seks sifrene den viser for å koble til.",
    "From bar %lld": "Fra takt %lld",
    "Get started": "Kom i gang",
    "Hear the band": "Hør bandet",
    "Hear the band or the recording": "Hør bandet eller opptaket",
    "Higher": "Høyere",
    "Home": "Hjem",
    "How hard?": "Hvor vanskelig?",
    "How should the score be?": "Hvordan skal partituret bli?",
    "Instrument Serif (SIL Open Font License 1.1)": "Instrument Serif (SIL Open Font License 1.1)",
    "Keep going": "Fortsett",
    "Key": "Toneart",
    "Keyboard": "Tastatur",
    "Last step": "Siste steg",
    "Laying out the pages": "Setter opp sidene",
    "Laying out the pages…": "Setter opp sidene …",
    "Library": "Bibliotek",
    "Links to streaming sites can't be downloaded. Play the music and record it instead.": "Lenker til strømmetjenester kan ikke lastes ned. Spill av musikken og ta den opp i stedet.",
    "Listening files": "Lyttefiler",
    "Lower": "Lavere",
    "MP3, WAV, M4A, MP4 and most other formats": "MP3, WAV, M4A, MP4 og de fleste andre formater",
    "Made on this Mac. Nothing goes online.": "Lages på denne Macen. Ingenting sendes til nettet.",
    "More formats": "Flere formater",
    "Move the pitch %@%lld semitones": "Flytt tonehøyden %@%lld halvtoner",
    "Music and video from streaming apps and shops are usually copy-protected.": "Musikk og video fra strømmeapper og butikker er som regel kopibeskyttet.",
    "MusicXML, MIDI, talking score, braille": "MusicXML, MIDI, talende partitur, punktskrift",
    "Mute my part": "Demp stemmen min",
    "Mute your part, slow it down, loop the hard bars.": "Demp stemmen din, sett ned tempoet, gjenta de vanskelige taktene.",
    "Mutes your part so you can play it with the band.": "Skrur av stemmen din så du kan spille den med bandet.",
    "My part (%@)": "Min stemme (%@)",
    "%@ (you)": "%@ (deg)",
    "Quartet": "Kvartett",
    "4 players, one on each part": "4 musikere, én på hver stemme",
    "Needs a recording of the whole group": "Trenger et opptak av hele gruppen",
    "Unavailable": "Ikke tilgjengelig",
    "Score (all 4 parts)": "Partitur (alle 4 stemmer)",
    "Needs Brasscribe on your computer": "Trenger Brasscribe på datamaskinen",
    "Next": "Neste",
    "Not sure? Choose Brass band.": "Usikker? Velg Brassband.",
    "Notes Brasscribe isn't sure about get a “?”. You decide.": "Toner Brasscribe er usikker på, får et «?». Du bestemmer.",
    "Notes Brasscribe isn't sure about have a “?” above them. A boxed “?” means very unsure.": "Toner Brasscribe er usikker på, har et «?» over seg. Et «?» i ramme betyr svært usikker.",
    "Nothing was heard": "Ingenting ble hørt",
    "Nothing was playing while you recorded.": "Ingenting spilte mens du tok opp.",
    "Now": "Nå",
    "Off": "Av",
    "On the computer, start Brasscribe with “brasscribe serve --lan”. It shows the pairing code, and this device finds it on the same network.": "Start Brasscribe på datamaskinen med «brasscribe serve --lan». Den viser koblingskoden, og denne enheten finner den på samme nettverk.",
    "On this device. Nothing goes online.": "På denne enheten. Ingenting sendes til nettet.",
    "On your computer. Nothing goes online.": "På datamaskinen din. Ingenting sendes til nettet.",
    "One bar of clicks before the music starts.": "Én takt med klikk før musikken starter.",
    "One instrument on its own can be written down here, with nothing sent anywhere. The listening files (about 40 MB) are downloaded once.": "Ett instrument alene kan skrives ned her, uten at noe sendes noe sted. Lyttefilene (omtrent 40 MB) lastes ned én gang.",
    "One player on their own, like you practising the cornet.": "Én musiker alene, som når du øver på kornett.",
    "One semitone higher": "Én halvtone høyere",
    "One semitone lower": "Én halvtone lavere",
    "Only %@": "Bare %@",
    "Only this": "Bare denne",
    "Only this: hear this part alone.": "Bare denne: hør bare denne stemmen.",
    "Open Brasscribe on your computer. When it's on the same network it's listed here: choose it, then type the six digits it shows.": "Åpne Brasscribe på datamaskinen. Når den er på samme nettverk, vises den her: velg den, og skriv de seks sifrene den viser.",
    "Open a recording": "Åpne et opptak",
    "Open a recording instead": "Åpne et opptak i stedet",
    "Other parts (%lld)": "Andre stemmer (%lld)",
    "Paired. Recordings can now be written down on your computer.": "Koblet til. Opptak kan nå skrives ned på datamaskinen.",
    "Pitch as written": "Tonehøyde som notert",
    "Play it, record it, or open a file. Brasscribe writes the parts for your band.": "Spill det, ta det opp eller åpne en fil. Brasscribe skriver stemmene for bandet ditt.",
    "Play the piece, record a rehearsal, or open a file you have.": "Spill stykket, ta opp en øvelse eller åpne en fil du har.",
    "Play your part in the room": "Spill stemmen din i rommet",
    "Plays the recording instead of the band, at the same place.": "Spiller opptaket i stedet for bandet, på samme sted.",
    "Plays these bars over and over.": "Spiller disse taktene om og om igjen.",
    "Practise with the band": "Øv med bandet",
    "Print": "Skriv ut",
    "Print…": "Skriv ut …",
    "Read aloud": "Les opp",
    "Record or import": "Ta opp eller åpne",
    "Record what's playing": "Ta opp det som spilles",
    "Recording": "Opptak",
    "Recordings stay on your own devices.": "Opptakene blir på dine egne enheter.",
    "Remove the listening files": "Fjern lyttefilene",
    "Repeat": "Gjenta",
    "Repeat %lld": "Gjenta %lld",
    "Repeat %lld–%lld": "Gjenta %lld–%lld",
    "Repeat bars": "Gjenta takt",
    "Repeat bars %lld to %lld…": "Gjenta takt %lld til %lld …",
    "Repeat from bar": "Gjenta fra takt",
    "Repeat this bar": "Gjenta denne takten",
    "Repeat to bar": "Gjenta til takt",
    "Save to Files": "Lagre i Filer",
    "Save…": "Lagre …",
    "Scores for your band, from": "Partitur for bandet ditt, fra",
    "Separating the soloist from the band": "Skiller solisten fra bandet",
    "Share or print": "Del eller skriv ut",
    "Share…": "Del …",
    "Show ? marks": "Vis ?-merker",
    "Show video": "Vis video",
    "Shows or hides the list of parts, where you can mute them.": "Viser eller skjuler listen over stemmer, der du kan skru dem av.",
    "Singing, guitars, keys, bass and drums.": "Sang, gitarer, keyboard, bass og trommer.",
    "Single-key shortcuts": "Hurtigtaster med én tast",
    "Six-digit code": "Sekssifret kode",
    "Soloist with band": "Solist med band",
    "Soloist with orchestra or band": "Solist med orkester eller band",
    "Sound from another app on this Mac": "Lyd fra en annen app på denne Macen",
    "Space plays and pauses, the arrow keys move by bar, and L, C, M, A and O switch the practice controls. Turn this off if you use speech control or a switch.": "Mellomrom spiller av og pauser, piltastene flytter én takt, og L, C, M, A og O slår øvekontrollene av og på. Slå dette av hvis du bruker talestyring eller bryterstyring.",
    "Speed %@": "Tempo %@",
    "Step %lld of %lld": "Steg %lld av %lld",
    "Step %lld of %lld · %@": "Steg %lld av %lld · %@",
    "Stop making this score?": "Slutte å lage dette partituret?",
    "Stop repeating": "Slutt å gjenta",
    "Streaming apps usually block recording. You hear the music, but the recording stays silent.": "Strømmeapper stopper som regel opptak. Du hører musikken, men opptaket blir stille.",
    "Switch between the score and the recording at the same place.": "Bytt mellom partituret og opptaket på samme sted.",
    "Text a screen reader can read aloud": "Tekst en skjermleser kan lese opp",
    "That didn't work. Check the six digits, and that the computer is on the same network.": "Det virket ikke. Sjekk de seks sifrene, og at datamaskinen er på samme nettverk.",
    "The band playing the score, to practise with": "Bandet spiller partituret, til å øve med",
    "The file may be damaged. Your recording is safe.": "Filen kan være skadet. Opptaket ditt er trygt.",
    "The listening files are ready.": "Lyttefilene er klare.",
    "The listening files couldn't be downloaded. Check the connection and try again.": "Lyttefilene kunne ikke lastes ned. Sjekk tilkoblingen og prøv igjen.",
    "The music app blocks recording. Streaming apps usually do.": "Musikkappen stopper opptak. Strømmeapper gjør som regel det.",
    "The recording is silent. This usually means one of these:": "Opptaket er stille. Det betyr som regel ett av disse:",
    "The score couldn't be arranged": "Partituret kunne ikke arrangeres",
    "The score couldn't be arranged this way. Try another choice.": "Partituret kunne ikke arrangeres slik. Prøv et annet valg.",
    "The score couldn't be made": "Partituret kunne ikke lages",
    "The score is still here to read. Try closing and opening it again.": "Partituret er fortsatt her å lese. Prøv å lukke og åpne det igjen.",
    "The sound can't play": "Lyden kan ikke spilles",
    "The system doesn't let any app record or read protected music.": "Systemet lar ingen apper ta opp eller lese beskyttet musikk.",
    "These files couldn't be made. Try fewer formats, or try again.": "Disse filene kunne ikke lages. Prøv færre formater, eller prøv igjen.",
    "This file can't be opened": "Denne filen kan ikke åpnes",
    "This isn't a score Brasscribe can read": "Dette er ikke et partitur Brasscribe kan lese",
    "This score can't be arranged again on this device. It opens as it is.": "Dette partituret kan ikke arrangeres på nytt på denne enheten. Det åpnes som det er.",
    "This score can't be opened": "Dette partituret kan ikke åpnes",
    "To bar %lld": "Til takt %lld",
    "Try again": "Prøv igjen",
    "Try an MP3, WAV, M4A or MP4 file.": "Prøv en MP3-, WAV-, M4A- eller MP4-fil.",
    "Turn a recording into": "Gjør et opptak om til",
    "Very unsure": "Svært usikker",
    "View": "Vis",
    "What": "Hva",
    "Which band?": "Hvilket band?",
    "Which notes": "Hvilke toner",
    "Working out the time left…": "Beregner tiden som er igjen …",
    "Write down solos on this device": "Skriv ned soloer på denne enheten",
    "Written down by Brasscribe · Page %lld of %lld": "Skrevet ned av Brasscribe · Side %lld av %lld",
    "Written is what you read on your part. Concert is how it sounds on a piano.": "Notert er det du leser i stemmen din. Klingende er slik det låter på et piano.",
    "You can change this later. Nothing is lost.": "Du kan endre dette senere. Ingenting går tapt.",
    "You can leave this screen. Brasscribe will tell you when the score is ready.": "Du kan forlate denne skjermen. Brasscribe sier fra når partituret er klart.",
    "You can start again from the recording.": "Du kan begynne på nytt fra opptaket.",
    "You get the solo part, plus the accompaniment arranged for brass band.": "Du får solostemmen, og akkompagnementet arrangert for brassband.",
    "Your answer decides how Brasscribe listens. It never guesses.": "Svaret ditt avgjør hvordan Brasscribe lytter. Den gjetter aldri.",
    "Your part (%lld)": "Din stemme (%lld)",
    "Your part is muted with “Mute my part”, so you can play along. “Only this” plays one part alone.": "Stemmen din dempes med «Demp stemmen min», så du kan spille med. «Bare denne» spiller én stemme alene.",
    "Zoom %@": "Zoom %@",
    "a score.": "et partitur.",
    "any recording.": "hvilket som helst opptak.",
    "of %lld": "av %lld",
    "of %lld · ♩ = %lld": "av %lld · ♩ = %lld",
    "of %lld · ♩ = %lld (slowed from %lld)": "av %lld · ♩ = %lld (ned fra %lld)",
    "one PDF per player": "én PDF per musiker",
    "talking score": "talende partitur",
    "to": "til",
    "your part": "din stemme",
    # the third usability review
    "%lld notes from written %@": "%lld toner fra notert %@",
    "%lld to check": "%lld å sjekke",
    "All (%lld)": "Alle (%lld)",
    "Bars %lld–%lld": "Takt %lld–%lld",
    "Full band": "Fullt band",
    "Keep the other %lld notes in this bar": "Behold de andre %lld tonene i takten",
    "Keep the other note in this bar": "Behold den andre tonen i takten",
    "Kept the notes in %@.": "Beholdt tonene i %@.",
    "Most of these are probably right. Listen to a bar, then keep the rest of it.": "De fleste av disse er nok riktige. Lytt til en takt, og behold resten av den.",
    "Most of these are probably right. Start with the %lld very unsure ones.": "De fleste av disse er nok riktige. Begynn med de %lld svært usikre.",
    "Start with the %lld very unsure ones.": "Begynn med de %lld svært usikre.",
    "MusicXML, MIDI and 2 more": "MusicXML, MIDI og 2 til",
    "Others (%lld)": "Andre (%lld)",
    "Recording, %@ %@": "Opptak, %@ %@",
    "Stop making the score": "Slutt å lage partituret",
    "Today": "I dag",
    "Yesterday": "I går",
    "Your part first: %lld notes in %@, %lld very unsure first.": "Stemmen din først: %lld toner i %@, %lld svært usikre først.",
    "Your part first: %lld notes in %@.": "Stemmen din først: %lld toner i %@.",
    "Yours (%lld)": "Din (%lld)",
    "breve": "brevis",
    "crotchet": "fjerdedelsnote",
    "demisemiquaver": "trettitodelsnote",
    "dotted %@": "punktert %@",
    "double-dotted %@": "dobbeltpunktert %@",
    "minim": "halvnote",
    "quaver": "åttendedelsnote",
    "semibreve": "helnote",
    "semiquaver": "sekstendedelsnote",
    # the third usability review, 2
    "Hear the recording": "Hør opptaket",
    "Ask again": "Spør på nytt",
    "Asks the computer to allow this device.": "Ber datamaskinen om å godkjenne denne enheten.",
    "Brasscribe on %@": "Brasscribe på %@",
    "Check that your computer shows %@, then choose Allow there.": "Sjekk at datamaskinen viser %@, og velg Godkjenn der.",
    "Connect": "Koble til",
    "Connected to %@": "Koblet til %@",
    "Do this once. This device stays paired, also when the computer restarts or gets a new address.": "Gjør dette én gang. Enheten forblir tilkoblet, også når datamaskinen starter på nytt eller får ny adresse.",
    "Forget": "Glem",
    "Forget this computer": "Glem denne datamaskinen",
    "Forget this computer?": "Glemme denne datamaskinen?",
    "Last answered": "Svarte sist",
    "Looking for %@ …": "Leter etter %@ …",
    "Not connected. You can still make scores on this Mac.": "Ikke tilkoblet. Du kan fortsatt lage partitur på denne Macen.",
    "Not connected. You can still make scores on this iPad.": "Ikke tilkoblet. Du kan fortsatt lage partitur på denne iPaden.",
    "Not connected. You can still make scores on this phone.": "Ikke tilkoblet. Du kan fortsatt lage partitur på denne telefonen.",
    "On %@, choose Allow. Check that it shows the same number:": "Velg Godkjenn på %@. Sjekk at den viser det samme tallet:",
    "Pair this Mac again": "Koble til Macen på nytt",
    "Pair this iPad again": "Koble til iPaden på nytt",
    "Pair this phone again": "Koble til telefonen på nytt",
    "Paired with %@.": "Koblet til %@.",
    "Pairing link": "Tilkoblingslenke",
    "Playing %@": "Spiller %@",
    "Port": "Port",
    "Scan the code": "Skann koden",
    "Scores already on this device stay. To use the computer again, pair once more.": "Partiturene som allerede er på denne enheten, blir værende. For å bruke datamaskinen igjen må du koble til på nytt.",
    "Server id": "Server-ID",
    "Space stops · K keeps": "Mellomrom stopper · K beholder",
    "Stopped": "Stoppet",
    "That code didn't work. Check the six digits on the computer, or choose the computer above and allow it there.": "Koden virket ikke. Sjekk de seks sifrene på datamaskinen, eller velg datamaskinen over og godkjenn den der.",
    "That code has been used or has run out. Show a new one on the computer, or choose the computer above and allow it there.": "Koden er brukt eller utløpt. Vis en ny på datamaskinen, eller velg datamaskinen over og godkjenn den der.",
    "That code isn't a Brasscribe pairing code.": "Det er ikke en tilkoblingskode fra Brasscribe.",
    "That isn't a Brasscribe pairing link. It starts with brasscribe://pair.": "Det er ikke en tilkoblingslenke fra Brasscribe. Den begynner med brasscribe://pair.",
    "The computer can't be reached. Check that Brasscribe on the computer says Running, and that both are on the same network.": "Får ikke kontakt med datamaskinen. Sjekk at Brasscribe på datamaskinen sier Kjører, og at begge er på samme nettverk.",
    "The computer didn't allow this device.": "Datamaskinen godkjente ikke denne enheten.",
    "The computer no longer recognises this Mac.": "Datamaskinen kjenner ikke igjen denne Macen lenger.",
    "The computer no longer recognises this iPad.": "Datamaskinen kjenner ikke igjen denne iPaden lenger.",
    "The computer no longer recognises this phone.": "Datamaskinen kjenner ikke igjen denne telefonen lenger.",
    "The request ran out before it was allowed on the computer.": "Forespørselen gikk ut før den ble godkjent på datamaskinen.",
    "This device's id": "Denne enhetens ID",
    "Use link": "Bruk lenken",
    "Waiting for your computer …": "Venter på datamaskinen …",
    "bars %lld to %lld": "takt %lld til %lld",
    "On your computer, click the Brasscribe mark in the menu bar (Mac) or the taskbar corner (Windows), and choose Pair a phone.": "Klikk på Brasscribe-merket i menylinjen (Mac) eller i hjørnet av oppgavelinjen (Windows) på datamaskinen, og velg Koble til en telefon.",
    "Without Brasscribe Bandroom, start the engine with “brasscribe serve --lan”.": "Uten Brasscribe Bandroom starter du motoren med «brasscribe serve --lan».",
    # Settings → Display → Appearance
    "Appearance": "Utseende",
    "Match system": "Følg systemet",
    "Light": "Lyst",
    "Pink": "Rosa",
    "🎺 Pink unlocked": "🎺 Rosa låst opp",
    "Version %@": "Versjon %@",
    "Dark": "Mørkt",
    "Increase contrast is on, so Brasscribe uses its high-contrast colours.": "Øk kontrast er på, så Brasscribe bruker høykontrastfargene.",
    # the music stand (design/music-stand.md §9)
    "%@ · %@ · bar %lld · %@": "%1$@ · %2$@ · takt %3$lld · %4$@",
    "%@ · bar %lld · %@": "%1$@ · takt %2$lld · %3$@",
    "%@, bar %lld of %lld, %@": "%1$@, takt %2$lld av %3$lld, %4$@",
    "Bar %lld · %@": "Takt %1$lld · %2$@",
    "Display": "Visning",
    "First page.": "Første side.",
    "Keep the stand controls visible": "Vis alltid knappene på notestativet",
    "Last page.": "Siste side.",
    "Leave": "Gå ut",
    "Leave the music stand": "Gå ut av notestativet",
    "Lock rotation": "Lås retningen",
    "Music Stand": "Notestativ",
    "Music stand": "Notestativ",
    "Music stand closed.": "Notestativet er lukket.",
    "Music stand controls": "Knappene på notestativet",
    "Music stand. %@, bar %lld of %lld.": "Notestativ. %1$@, takt %2$lld av %3$lld.",
    "Next page": "Neste side",
    "Only my part": "Bare stemmen min",
    "Open on the music stand": "Åpne på notestativet",
    "Page %lld of %lld, bars %lld to %lld.": "Side %1$lld av %2$lld, takt %3$lld til %4$lld.",
    "Page turners and pedals work when they send arrow keys or Page Up and Page Down. Space starts and stops the music.": "Sidevendere og pedaler virker når de sender piltaster eller Page Up og Page Down. Mellomrom starter og stopper musikken.",
    "Previous page": "Forrige side",
    "Rotation locked": "Retningen er låst",
    "Rotation locked. The music stays this way up.": "Retningen er låst. Notene blir stående slik.",
    "Space plays and pauses, the arrow keys move by bar, F opens the music stand, and L, C, M, A and O switch the practice controls. Turn this off if you use speech control or a switch.": "Mellomrom spiller av og pauser, piltastene flytter én takt, F åpner notestativet, og L, C, M, A og O slår øvekontrollene av og på. Slå dette av hvis du bruker talestyring eller bryterstyring.",
    "Tap the music to show the controls.": "Trykk på notene for å vise knappene.",
    "The music alone, for playing from the stand (F)": "Bare notene, til å spille fra notestativet (F)",
    "The music turns with the phone again.": "Notene snur seg med telefonen igjen.",
    "To keep a tablet one way up, use the rotation lock in Control Centre (iPad) or Quick Settings (Android).": "Bruk retningslåsen i kontrollsenteret (iPad) eller hurtiginnstillingene (Android) for å holde nettbrettet i én retning.",
    "Turn the pages while playing": "Bla om mens musikken spiller",
    " flat": " b",
    "%@ (as usual)": "%@ (som vanlig)",
    "%@ on your part": "%@ på stemmen din",
    "%@, as it sounds": "%@, klingende",
    "A solo recording gives one part: yours.": "Et soloopptak gir én stemme: din.",
    "Arranged from the band's harmony": "Arrangert ut fra harmoniene i bandet",
    "Baritone": "Baryton",
    "Bass clef, as it sounds": "F-nøkkel, klingende",
    "Brasscribe shows your part first and mutes it when you play along. You can change it in Settings.": "Brasscribe viser stemmen din først og demper den når du spiller med. Du kan endre det i Innstillinger.",
    "Brasscribe wrote down the notes it heard for this part.": "Brasscribe skrev ned tonene den hørte for denne stemmen.",
    "B♭": "B",
    "Check the other parts": "Sjekk de andre stemmene",
    "Choose which part you play.": "Velg hvilken stemme du spiller.",
    "Choose your instrument, or “I conduct or listen”.": "Velg instrumentet ditt, eller «Jeg dirigerer eller lytter».",
    "Cornet": "Kornett",
    "E♭": "Ess",
    "From the recording": "Fra opptaket",
    "From your recording": "Fra opptaket ditt",
    "I conduct or listen": "Jeg dirigerer eller lytter",
    "Instrument": "Instrument",
    "Make this my part": "Gjør til min stemme",
    "New scores open on your part. Scores you already have keep the part you chose for them.": "Nye partiturer åpner på stemmen din. Partiturer du har fra før, beholder stemmen du valgte.",
    "Nobody played the %@ part on its own in the recording, so Brasscribe wrote it from the chords it heard. There are no notes of yours to check.": "Ingen spilte %@ alene i opptaket, så Brasscribe skrev stemmen ut fra akkordene den hørte. Det er ingen toner av dine å sjekke.",
    "Nobody played this part on its own in the recording. Brasscribe wrote it from the chords it heard, so it can differ from your printed part.": "Ingen spilte denne stemmen alene i opptaket. Brasscribe skrev den ut fra akkordene den hørte, så den kan avvike fra noten din.",
    "None": "Ingen",
    "Not now": "Ikke nå",
    "Not set": "Ikke valgt",
    "Says what this means.": "Forklarer hva dette betyr.",
    "Show my part": "Vis stemmen min",
    "Tenor Horn": "Althorn",
    "Soprano": "Sopran",
    "E♭ cornet": "Ess-kornett",
    "The quartet has no %@. Your part here is %@, the closest, in bass clef as it sounds.": "Kvartetten har ingen %1$@. Her er stemmen din %2$@, den nærmeste, i F-nøkkel, klingende.",
    "The quartet has no %@. Your part here is %@, the closest: the same key and clef.": "Kvartetten har ingen %1$@. Her er stemmen din %2$@, den nærmeste: samme stemming og nøkkel.",
    "The quartet has no %@. Your part here is %@, written for %@.": "Kvartetten har ingen %1$@. Her er stemmen din %2$@, skrevet for %3$@.",
    "The quartet has no percussion part. Brasscribe opens every part.": "Kvartetten har ingen slagverkstemme. Brasscribe åpner alle stemmene.",
    "This small band has no %@. Your part here is %@, the closest, in bass clef as it sounds.": "Det lille bandet har ingen %1$@. Her er stemmen din %2$@, den nærmeste, i F-nøkkel, klingende.",
    "This small band has no %@. Your part here is %@, the closest: the same key and clef.": "Det lille bandet har ingen %1$@. Her er stemmen din %2$@, den nærmeste: samme stemming og nøkkel.",
    "This small band has no %@. Your part here is %@, written for %@.": "Det lille bandet har ingen %1$@. Her er stemmen din %2$@, skrevet for %3$@.",
    "This small band has no percussion part. Brasscribe opens every part.": "Det lille bandet har ingen slagverkstemme. Brasscribe åpner alle stemmene.",
    "Treble clef": "G-nøkkel",
    "Treble clef in %@": "G-nøkkel i %@",
    "Trombone": "Trombone",
    "What do you play?": "Hva spiller du?",
    "What you play": "Hva du spiller",
    "Which part?": "Hvilken stemme?",
    "Who played this?": "Hvem spilte?",
    "Who plays the tune?": "Hvem spiller melodien?",
    "Write for another instrument…": "Skriv for et annet instrument …",
    "You read": "Du leser",
    "You: %@": "Deg: %@",
    "Your instrument": "Instrumentet ditt",
    "Your part": "Stemmen din",
    "Your part is arranged": "Stemmen din er arrangert",
    "Your part is arranged. %@": "Stemmen din er arrangert. %@",
    "bass clef, as it sounds": "F-nøkkel, klingende",
    "concert pitch": "klingende",
    "in E♭": "i Ess",
    "treble clef": "G-nøkkel",
    "treble clef in %@": "G-nøkkel i %@",
    "your part: %@": "stemmen din: %@",
    "The small band has no %@ — showing %@": "Det lille bandet har ingen %1$@ — viser %2$@",
    "The quartet has no %@ — showing %@": "Kvartetten har ingen %1$@ — viser %2$@",
    "The small band has no percussion part — showing every part": "Det lille bandet har ingen slagverkstemme — viser alle stemmene",
    "The quartet has no percussion part — showing every part": "Kvartetten har ingen slagverkstemme — viser alle stemmene",
    "Written (%@)": "Notert (%@)",
    "The band sounds are missing.": "Lydene til bandet mangler.",
    "Details": "Detaljer",
    "The band sounds are missing. Details": "Lydene til bandet mangler. Detaljer",
    "Practice": "Øving",
    "Close": "Lukk",
    "Yours (arranged)": "Din (arrangert)",
    "Your part (arranged)": "Din stemme (arrangert)",
    "page %lld of %lld": "side %1$lld av %2$lld",
    "pages %lld–%lld of %lld": "side %1$lld–%2$lld av %3$lld",
}

INFO_NB = {
    "CFBundleDisplayName": "Brasscribe Play",
    "NSMicrophoneUsageDescription": "Brasscribe Play tar opp spillingen din for å gjøre den om til noter.",
    "NSAudioCaptureUsageDescription": "Brasscribe Play tar opp lyden som spilles på denne Macen for å gjøre den om til noter.",
    "NSLocalNetworkUsageDescription": "Brasscribe Play snakker med Brasscribe på din egen datamaskin for å skrive ned tonene i opptak.",
    "NSCameraUsageDescription": "Brasscribe Play skanner koden datamaskinen viser, for å koble seg til den.",
}


def entry(nb: str) -> dict:
    return {"localizations": {"nb": {"stringUnit": {"state": "translated", "value": nb}}}}


def main(root: str) -> None:
    keys = set()
    for f in glob.glob(root + "/**/*.stringsdata", recursive=True):
        if "BrasscribePlay_" not in f or "Tests" in f:
            continue
        for table in json.load(open(f)).get("tables", {}).values():
            keys.update(e["key"] for e in table)
    keys.discard("")
    # translations already in the catalog (added by hand or by other tools) are kept;
    # the table above wins where both have one
    existing = {}
    try:
        for k, v in json.load(open("App/Localizable.xcstrings")).get("strings", {}).items():
            nb = v.get("localizations", {}).get("nb", {}).get("stringUnit", {}).get("value")
            if nb:
                existing[k] = nb
    except FileNotFoundError:
        pass
    strings = {}
    missing = []
    for k in sorted(keys):
        if k in NB:
            strings[k] = entry(NB[k])
        elif k in existing:
            strings[k] = entry(existing[k])
        else:
            strings[k] = {}
            missing.append(k)
    catalog = {"sourceLanguage": "en", "strings": strings, "version": "1.0"}
    with open("App/Localizable.xcstrings", "w") as f:
        json.dump(catalog, f, indent=2, ensure_ascii=False, sort_keys=True)
    info = {"sourceLanguage": "en", "version": "1.0",
            "strings": {k: entry(v) for k, v in INFO_NB.items()}}
    with open("App/InfoPlist.xcstrings", "w") as f:
        json.dump(info, f, indent=2, ensure_ascii=False, sort_keys=True)
    print(f"{len(strings)} strings, {len(missing)} without Norwegian", file=sys.stderr)
    for k in missing:
        print("  missing:", k, file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
