/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Audio */
        post: operations["uploadAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conformance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conformance
         * @description Rust-core conformance results as written (every *.json in BRASSCRIBE_CONFORMANCE_REPORTS), plus `_file`.
         */
        get: operations["listConformanceReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["listJobs"];
        put?: never;
        /** Create Job */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Job From Upload
         * @description Upload audio and start a job in one request (same as uploadAudio followed by createJob).
         */
        post: operations["createJobFromUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancelJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["listJobArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["getJobArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio */
        get: operations["getRenderedAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Job
         * @description composition.json byte equality and per-part MusicXML note content against a reference or another job.
         */
        get: operations["compareJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/composition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Composition */
        get: operations["getComposition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Input
         * @description The job's original input audio (for A/B listening).
         */
        get: operations["getJobInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["getJobManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/midi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Midi */
        get: operations["getMidi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/musicxml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Musicxml */
        get: operations["getMusicXml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pdf */
        get: operations["getPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Job
         * @description Run a job again from its manifest (same input, profile, title and parameters).
         */
        post: operations["rerunJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/roundtrip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Roundtrip
         * @description Stored MuseScore round-trip result, or status not_run (start it with runRoundtrip).
         */
        get: operations["getRoundtrip"];
        put?: never;
        /**
         * Run Roundtrip
         * @description Re-export the job's MusicXML through MuseScore and compare every part's sounding pitches (takes seconds).
         */
        post: operations["runRoundtrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stages
         * @description Every stage of a run with its output files (stems, layers, MIDI, beats, Composition, MusicXML ...).
         */
        get: operations["listJobStages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/stages/{stage}/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stage File */
        get: operations["getStageFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Validation
         * @description Arranger warnings (range problems) for the job's Composition, by part, bar and beat.
         */
        get: operations["getValidation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair */
        post: operations["pairDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Parity
         * @description Model-conversion parity reports as written (every *.json in BRASSCRIBE_PARITY_REPORTS), plus `_file`.
         */
        get: operations["listParityReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["listProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List References
         * @description Reference outputs under <data>/golden (read only).
         */
        get: operations["listReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/references/{name}/files/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reference File */
        get: operations["getReferenceFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Adapters
         * @description Adapters with version, environment fingerprint, device, licence and model weights.
         */
        get: operations["listAdapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description Eval sets under <data>/eval: size, items, licence, cached model outputs and how to build a missing set.
         */
        get: operations["listDatasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Recordings that can start a job without an upload: captures and eval-set items (createJob source_id).
         */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suites */
        get: operations["listSuites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suites/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suite History
         * @description Every stored suite result, newest first (from `brasscribe bench` and runSuite).
         */
        get: operations["listSuiteHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suites/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Suite
         * @description Run a suite or group (cpu, all) against eval/baselines.json; the result is stored in the history.
         */
        post: operations["runSuite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdapterInfo */
        AdapterInfo: {
            /** Device */
            device: string;
            /** Fingerprint */
            fingerprint: string;
            /** Heavy */
            heavy: boolean;
            /** Licence */
            licence?: string | null;
            /** Models */
            models: components["schemas"]["ModelFile"][];
            /** Name */
            name: string;
            /** Version */
            version?: string | null;
        };
        /** Artifact */
        Artifact: {
            /** Bytes */
            bytes: number;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** AudioRef */
        AudioRef: {
            /** Audio Id */
            audio_id: string;
            /** Bytes */
            bytes: number;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
        };
        /** BenchRun */
        BenchRun: {
            /** Created */
            created: string;
            /** Device */
            device?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Id */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "cached" | "live";
            /** Passed */
            passed: boolean;
            /** Suites */
            suites: components["schemas"]["SuiteResult"][];
            /**
             * Target
             * @description suite or group that was run
             */
            target: string;
        };
        /** Body_createJobFromUpload */
        Body_createJobFromUpload: {
            /** File */
            file: string;
            /**
             * Profile
             * @default orchestra-with-soloist
             */
            profile: string;
            /**
             * Render Audio
             * @default true
             */
            render_audio: boolean;
            /** Title */
            title?: string | null;
        };
        /** Body_uploadAudio */
        Body_uploadAudio: {
            /** File */
            file: string;
        };
        /** Check */
        Check: {
            /** Baseline */
            baseline: number | null;
            /** Metric */
            metric: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "regressed" | "improved" | "missing" | "skipped" | "new";
            /** Tolerance */
            tolerance: number;
            /** Value */
            value: number | null;
        };
        /** Comparison */
        Comparison: {
            /** Composition Identical */
            composition_identical: boolean;
            /**
             * Extra Files
             * @description parts/*.musicxml and separation-check.json the reference has: identical?
             */
            extra_files?: {
                [key: string]: boolean;
            };
            /** Musicxml Identical */
            musicxml_identical: boolean;
            /** Notes Identical */
            notes_identical: number;
            /** Notes Total */
            notes_total: number;
            /** Ok */
            ok: boolean;
            /** Parts */
            parts: components["schemas"]["PartComparison"][];
            /** Parts Identical */
            parts_identical: number;
            /** Parts Total */
            parts_total: number;
        };
        /**
         * Composition
         * @description The canonical score (brasscribe_music.score_model.Composition): concert pitch, integer ticks.
         */
        Composition: {
            /**
             * Beat Times
             * @description seconds of beat 0, 1, 2 ...
             */
            beat_times?: number[];
            /**
             * First Downbeat
             * @default 0
             */
            first_downbeat: number;
            /** Keys */
            keys: components["schemas"]["KeySig"][];
            /** Meters */
            meters: components["schemas"]["Meter"][];
            /**
             * Ticks Per Beat
             * @default 24
             */
            ticks_per_beat: number;
            /** Title */
            title: string;
            /** Voices */
            voices: components["schemas"]["Voice"][];
        } & {
            [key: string]: unknown;
        };
        /** Dataset */
        Dataset: {
            /** Bytes */
            bytes: number;
            /**
             * Cached Outputs
             * @description model output files present for every item (e.g. muscriptor-medium.mid)
             */
            cached_outputs: string[];
            /**
             * Download
             * @description how to build the set when it is missing
             */
            download?: string | null;
            /** Files */
            files: number;
            /** Items */
            items: number;
            /** Licence */
            licence?: string | null;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Present */
            present: boolean;
            /** Source Url */
            source_url?: string | null;
        };
        /** FileRef */
        FileRef: {
            /** Bytes */
            bytes: number;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256?: string | null;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Auth Required
             * @description whether this client must send a bearer token
             */
            auth_required: boolean;
            /**
             * Device
             * @description accelerator torch adapters use on this host: cuda, mps or cpu
             */
            device: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** Job */
        Job: {
            /** Audio Id */
            audio_id?: string | null;
            /** Created */
            created: number;
            /** Error */
            error?: string | null;
            /** Finished */
            finished?: number | null;
            /** Id */
            id: string;
            /**
             * Outputs
             * @description names fetchable under /v1/jobs/{id}/artifacts/{name}
             */
            outputs?: string[];
            /**
             * Previous Run Id
             * @description the job this one re-runs, if any
             */
            previous_run_id?: string | null;
            /** Profile */
            profile: string;
            /**
             * Progress
             * @description share of stages finished, 0..1
             * @default 0
             */
            progress: number;
            /** Stages */
            stages: components["schemas"]["StageState"][];
            /** Started */
            started?: number | null;
            /** Status */
            status: ("queued" | "running" | "succeeded" | "failed" | "cancelled") | "unknown";
            /** Title */
            title?: string | null;
        };
        /**
         * JobCreate
         * @description Exactly one of audio_id (an upload), source_id (from listSources) or path (a file inside the data directory).
         */
        JobCreate: {
            /**
             * Allow Heavy
             * @description allow heavy models to run on cache misses
             * @default true
             */
            allow_heavy: boolean;
            /** Audio Id */
            audio_id?: string | null;
            /**
             * Path
             * @description audio file path; must lie inside the engine's data directory
             */
            path?: string | null;
            /**
             * Profile
             * @default orchestra-with-soloist
             */
            profile: string;
            /**
             * Render Audio
             * @description also render an MP3 of the score
             * @default true
             */
            render_audio: boolean;
            /** Source Id */
            source_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** KeySig */
        KeySig: {
            /** Fifths */
            fifths: number;
            /**
             * Mode
             * @default major
             */
            mode: string;
            /** Tick */
            tick: number;
        } & {
            [key: string]: unknown;
        };
        /** Meter */
        Meter: {
            /**
             * Beat Unit
             * @default 4
             */
            beat_unit: number;
            /** Beats */
            beats: number;
            /** Tick */
            tick: number;
        } & {
            [key: string]: unknown;
        };
        /** ModelFile */
        ModelFile: {
            /** Bytes */
            bytes?: number | null;
            /** Licence */
            licence?: string | null;
            /** Name */
            name: string;
            /** Present */
            present: boolean;
            /** Revision */
            revision?: string | null;
            /** Sha256 */
            sha256?: string | null;
        };
        /** Note */
        Note: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Dur
             * @description notated duration in ticks
             */
            dur: number;
            /** Offset S */
            offset_s?: number | null;
            /** Onset S */
            onset_s?: number | null;
            /**
             * Pitch
             * @description concert MIDI pitch
             */
            pitch: number;
            /** Sources */
            sources?: string[];
            /**
             * Start
             * @description ticks from the first downbeat (negative in a pickup)
             */
            start: number;
        } & {
            [key: string]: unknown;
        };
        /** PairRequest */
        PairRequest: {
            /**
             * Code
             * @description pairing code shown by the engine (brasscribe serve --host 0.0.0.0)
             */
            code: string;
            /** Device Name */
            device_name?: string | null;
        };
        /** PairResponse */
        PairResponse: {
            /**
             * Token
             * @description send as 'Authorization: Bearer <token>' on every request
             */
            token: string;
        };
        /** PartComparison */
        PartComparison: {
            /** Identical */
            identical: boolean;
            /** Name */
            name: string;
            /** Notes */
            notes: number;
            /** Reference Notes */
            reference_notes: number;
        };
        /** ProfileInfo */
        ProfileInfo: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Pipeline */
            pipeline: string;
            /** Stages */
            stages: string[];
            /**
             * Validated
             * @description checked end to end against a golden output
             */
            validated: boolean;
        };
        /** Reference */
        Reference: {
            /** Files */
            files: components["schemas"]["FileRef"][];
            /** Name */
            name: string;
        };
        /** RerunRequest */
        RerunRequest: {
            /**
             * Allow Heavy
             * @default true
             */
            allow_heavy: boolean;
            /**
             * Cold
             * @description stages or kinds to run even on a cache hit, or 'all'
             */
            cold?: string[];
        };
        /** Roundtrip */
        Roundtrip: {
            /** Detail */
            detail?: string | null;
            /** Musescore */
            musescore?: string | null;
            /**
             * Notes In
             * @description pitched notes in the arrangement
             */
            notes_in?: number | null;
            /**
             * Notes Out
             * @description pitched notes read back from MuseScore's export
             */
            notes_out?: number | null;
            /** Part Results */
            part_results?: components["schemas"]["RoundtripPart"][];
            /** Parts */
            parts?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "not_run";
        };
        /** RoundtripPart */
        RoundtripPart: {
            /**
             * Match
             * @description null for unpitched parts, which are not compared
             */
            match?: boolean | null;
            /** Name */
            name: string;
            /** Notes */
            notes: number;
            /** Sound */
            sound?: string | null;
        };
        /** Source */
        Source: {
            /** Dataset */
            dataset?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "capture" | "dataset";
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** StageArtifacts */
        StageArtifacts: {
            /** Device */
            device?: string | null;
            /** Files */
            files: components["schemas"]["FileRef"][];
            /** Key */
            key?: string | null;
            /** Kind */
            kind?: string | null;
            /** Seconds */
            seconds?: number | null;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
        };
        /** StageState */
        StageState: {
            /** Device */
            device?: string | null;
            /** Kind */
            kind?: string | null;
            /** Name */
            name: string;
            /** Seconds */
            seconds?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "started" | "cached" | "imported" | "ran" | "failed" | "skipped";
        };
        /** SuiteHistoryEntry */
        SuiteHistoryEntry: {
            /** Checks */
            checks: components["schemas"]["Check"][];
            /** Device */
            device?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /**
             * Manifest
             * @description history file this entry came from
             */
            manifest?: string | null;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Reason */
            reason?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "skipped" | "error";
            /** Suite */
            suite: string;
            /** Target */
            target: string;
            /**
             * Time
             * @description unix seconds
             */
            time: number;
        };
        /** SuiteInfo */
        SuiteInfo: {
            /**
             * Cpu
             * @description runs on CPU from cached model outputs
             */
            cpu: boolean;
            /** Description */
            description: string;
            /** Name */
            name: string;
            /**
             * Requires
             * @description data paths the suite reads, relative to the data directory
             */
            requires: string[];
        };
        /** SuiteResult */
        SuiteResult: {
            /** Checks */
            checks?: components["schemas"]["Check"][];
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Reason */
            reason?: string | null;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
            /**
             * Skipped Parts
             * @description eval sets (metric prefixes) without data
             */
            skipped_parts?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "skipped" | "error";
            /** Suite */
            suite: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Bar */
            bar?: number | null;
            /** Beat */
            beat?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "range" | "crossing" | "other";
            /** Message */
            message: string;
            /** Part */
            part?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "error";
            /** Tick */
            tick?: number | null;
        };
        /** Voice */
        Voice: {
            /** Id */
            id: string;
            /** Instrument Hint */
            instrument_hint?: string | null;
            /** Layer */
            layer?: string | null;
            /** Notes */
            notes: components["schemas"]["Note"][];
            /**
             * Role
             * @enum {string}
             */
            role: "melody" | "countermelody" | "harmony" | "bass" | "rhythm";
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadAudio: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadAudio"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listConformanceReports: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createJobFromUpload: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createJobFromUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listJobArtifacts: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJobArtifact: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRenderedAudio: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compareJob: {
        parameters: {
            query?: {
                /** @description name from listReferences */
                reference?: string | null;
                /** @description another job id */
                job?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getComposition: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Composition JSON, byte for byte as written by the pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Composition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamJobEvents: {
        parameters: {
            query?: {
                /** @description resume after this event id */
                after?: number;
            };
            header?: {
                "last-event-id"?: string | null;
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events; each `data:` line is a JobEvent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        /** Device */
                        device?: string | null;
                        /** Error */
                        error?: string | null;
                        /**
                         * Fraction
                         * @description share of the job's stages done (stage events)
                         */
                        fraction?: number | null;
                        /** Id */
                        id: number;
                        /** Kind */
                        kind?: string | null;
                        /** Message */
                        message?: string | null;
                        /** Run */
                        run: string;
                        /** Seconds */
                        seconds?: number | null;
                        /** Stage */
                        stage?: string | null;
                        /** Status */
                        status?: string | null;
                        /** Time */
                        time: number;
                        /**
                         * Type
                         * @enum {string}
                         */
                        type: "job" | "stage" | "log";
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJobInput: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJobManifest: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMidi: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/midi": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMusicXml: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.recordare.musicxml+xml": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPdf: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerunJob: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RerunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRoundtrip: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roundtrip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runRoundtrip: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roundtrip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listJobStages: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageArtifacts"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStageFile: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                stage: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getValidation: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationIssue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pairDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description wrong pairing code */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listParityReports: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listReferences: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reference"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getReferenceFile: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listAdapters: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDatasets: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSuites: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSuiteHistory: {
        parameters: {
            query?: {
                /** @description only results of this suite */
                suite?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runSuite: {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
