import AVFoundation
import Foundation
import Testing
import ScoreKit
@testable import PlaybackKit

func partSoundVectors() -> URL? {
    guard let r = repoRoot() else { return nil }
    let f = r.appending(path: "sounds/partsound-vectors.json")
    return FileManager.default.fileExists(atPath: f.path) ? f : nil
}

/// Every vector in sounds/partsound-vectors.json (generated by sounds/partsound.py, the reference
/// resolver the Android, Windows and Studio players also test against) resolves identically.
@Test(.enabled(if: partSoundVectors() != nil)) func resolverMatchesSharedVectors() throws {
    let root = try #require(repoRoot())
    let resolver = try PartSoundResolver(mapping: root.appending(path: "sounds/mapping.json"))
    let vectorsURL = try #require(partSoundVectors())
    let doc = try #require(try JSONSerialization.jsonObject(with: Data(contentsOf: vectorsURL)) as? [String: Any])
    let vectors = try #require(doc["vectors"] as? [[String: Any]])
    #expect(vectors.count > 20)
    for v in vectors {
        let name = try #require(v["name"] as? String)
        let got = resolver.resolve(name: name, instrument: v["instrument"] as? String, program: (v["program"] as? NSNumber)?.intValue)
        guard let e = v["expect"] as? [String: Any] else {
            #expect(got == nil, "\(name) should stay unresolved")
            continue
        }
        let g = try #require(got, "\(name) did not resolve")
        #expect(g.part == e["part"] as? String, "\(name): part")
        #expect(g.step == e["step"] as? String, "\(name): step")
        #expect(g.program == (e["program"] as? NSNumber)?.intValue, "\(name): program")
        #expect(g.bank == (e["bank"] as? NSNumber)?.intValue, "\(name): bank")
        #expect(abs(g.channelGainDB - ((e["channel_gain_db"] as? NSNumber)?.doubleValue ?? .nan)) < 1e-9, "\(name): gain")
        #expect(g.percussion == (e["percussion"] as? Bool), "\(name): percussion")
    }
}

/// Every part of every lineup gets its own band preset, by its exact name.
@Test(.enabled(if: repoRoot() != nil)) func everyLineupPartHasABandPreset() throws {
    let root = try #require(repoRoot())
    let mapping = root.appending(path: "sounds/mapping.json")
    let resolver = try PartSoundResolver(mapping: mapping)
    let m = try #require(try JSONSerialization.jsonObject(with: Data(contentsOf: mapping)) as? [String: Any])
    let lineups = try #require(m["lineups"] as? [String: Any])
    var count = 0
    for (lineup, parts) in lineups {
        guard let parts = parts as? [String] else { continue }
        for p in parts {
            let r = resolver.resolve(name: p)
            #expect(r?.step == "exact", "\(lineup): \(p) has no preset of its own")
            count += 1
        }
    }
    #expect(count >= 30)
}

@Test func normalizeFollowsTheMapping() {
    #expect(PartSoundResolver.normalize("  E♭\u{00A0}Bass ") == "eb bass")
    #expect(PartSoundResolver.normalize("Solo\tCornet") == "solo cornet")
}

@Test func missingBandSoundsIsAnExplicitBasicTier() {
    let bank = SoundBank(general: nil)
    #expect(bank.tier == .basic)
    #expect(bank.bandStatus.isMissing)
    let (_, status) = BandSounds.locateBand(bundle: .main)
    if status.isMissing { #expect(!status.details.isEmpty, "the details say where the band sounds were looked for") }
}

/// Without any environment variable, a checkout finds the band SoundFont and every golden part
/// (and the quartet names) plays a band preset, never the General MIDI bank.
@Test(.enabled(if: bandSoundFont() != nil)) func bandSoundFontIsTheDefault() throws {
    let (band, status) = BandSounds.locateBand(bundle: .main)
    let b = try #require(band, "not found: \(status.details)")
    #expect(!status.isMissing)
    for name in ["1st Cornet", "2nd Cornet", "Tenor Horn", "Euphonium", "Tuba", "Baritone", "Trombone"] {
        let s = try #require(b.sound(for: name, instrumentSound: nil, midiProgram: nil), "\(name)")
        #expect(s.bankMSB == 0x79)
    }
    #expect(b.sound(for: "Piano", instrumentSound: "keyboard.piano", midiProgram: 1) == nil)
}

private func unisonScore() throws -> Score {
    // Two cornet parts on the same GM program (so ScoreKit's MIDIWriter puts them on one MIDI
    // channel) play the same pitch: part 1 a whole note, part 2 a quarter note then rests.
    func part(_ id: String, _ notes: String) -> String {
        """
        <part id="\(id)"><measure number="1"><attributes><divisions>1</divisions><key><fifths>0</fifths></key>
        <time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>
        <direction><sound tempo="120"/></direction>\(notes)</measure></part>
        """
    }
    func header(_ id: String, _ name: String) -> String {
        """
        <score-part id="\(id)"><part-name>\(name)</part-name><score-instrument id="\(id)-I1"><instrument-name>Cornet</instrument-name>
        <instrument-sound>brass.cornet</instrument-sound></score-instrument><midi-instrument id="\(id)-I1"><midi-channel>1</midi-channel>
        <midi-program>57</midi-program></midi-instrument></score-part>
        """
    }
    let n = "<note><pitch><step>F</step><octave>4</octave></pitch><duration>%d</duration><type>%@</type></note>"
    let rest = "<note><rest/><duration>3</duration></note>"
    let xml = """
    <?xml version="1.0" encoding="UTF-8"?>
    <score-partwise version="4.0"><part-list>\(header("P1", "Cornet 1"))\(header("P2", "Cornet 2"))</part-list>
    \(part("P1", String(format: n, 4, "whole")))\(part("P2", String(format: n, 1, "quarter") + rest))</score-partwise>
    """
    return try MusicXMLParser.parse(Data(xml.utf8))
}

/// One part's note-off never ends another part's note on the same pitch: the whole note keeps
/// sounding after the quarter note in the other part stops.
@Test(.enabled(if: bandSoundFont() != nil)) func unisonNoteOffDoesNotCutTheOtherPart() throws {
    let score = try unisonScore()
    #expect(score.parts.count == 2)
    #expect(MIDIWriter.channels(for: score).values.count == 2)
    let bank = SoundBank.locate(bundle: .main)
    let e = try PlaybackEngine(score: score, soundBank: bank, roomIR: nil, offlineFormat: PlaybackEngine.offlineFormat())
    e.roomOn = false
    #expect(e.sampler(for: score.parts[0]) !== e.sampler(for: score.parts[1]))
    let both = try e.renderScore(fromBeat: 0, beats: 4)
    e.setSoloed(score.parts[0].id, true)
    let alone = try e.renderScore(fromBeat: 0, beats: 4)
    let sr = Int(both.format.sampleRate)
    // Part 2's note ends at 0.5 s. Part 1 must keep its own level after that: compare 1.0–1.8 s
    // with part 1 played alone, and with part 1's own level before 0.5 s. Levels are relative: the
    // band presets are level-matched to one quiet reference (sounds/build.py TARGET_K_DB), so a
    // single mf cornet sits near -60 dBFS here and an absolute floor says nothing about cutting.
    let a = both.rms(from: sr, to: sr * 18 / 10), b = alone.rms(from: sr, to: sr * 18 / 10)
    let before = alone.rms(from: sr / 10, to: sr * 4 / 10)
    print("UNISON rms both \(a), part 1 alone \(b), part 1 before the other's note-off \(before)")
    #expect(b > 1e-4, "part 1 is silent")
    #expect(abs(20 * log10(a / b)) < 1.5, "part 1 lost level after part 2's note-off")
    #expect(abs(20 * log10(a / before)) < 3, "part 1 is quieter after part 2's note-off than before it")
}
