/* brasscribe core C API. Generated by cbindgen from brasscribe-ffi/src/c_api.rs; do not edit. */

#ifndef BRASSCRIBE_H
#define BRASSCRIBE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define BC_OK 0

#define BC_INVALID 1

#define BC_FAILED 2

#define BC_NULL 3

#define BC_PANIC 4

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Release a string returned by this library. Null is ignored.
void bc_string_free(char *s);

// Library version, e.g. "0.1.0". Free with `bc_string_free`.
char *bc_version(void);

// Parse a Composition JSON and write its canonical form to `*out`.
int32_t bc_composition_normalize(const char *json, char **out, char **err);

// Arrange a Composition JSON for brass band and write MusicXML to `*out`.
// `arranger`: "auto", "layers" or "minimal" (null = "auto").
int32_t bc_arrange_musicxml(const char *composition_json,
                            const char *arranger,
                            char **out,
                            char **err);

// Re-arrange a Composition JSON for a lineup and difficulty and write MusicXML to `*out`.
// `options` may be null (defaults) or
// `{"lineup": "band" | "minimal" | "quartet", "difficulty": "faithful" | "standard" | "easier",
//   "key": "Bb" | null, "transpose": null, "seat": ..., "reads": ..., "lead": ...}` (the keys of
//   [`bc_arrange_layers_song`]); `transpose`
// is the total from the recording, as in `arrange_musicxml_with`.
int32_t bc_arrange_with(const char *composition_json, const char *options, char **out, char **err);

// Solo-with-band arrangement from six MIDI files (solo SwiftF0, solo
// MuScriptor, solo Basic Pitch, bass, orchestra, drums, in that order) and a
// beat table. Writes the Composition JSON to `*out_composition` and MusicXML
// to `*out_musicxml`.
//
// `options_json` may be null (defaults) or
// `{"solo_contour": {"times": [...], "pitch_hz": [...], "loudness_db": [...]},
//   "free_time": true, "free_tempo": null, "gate": true, "beat_cleanup": true,
//   "key_changes": true, "lineup": "band" | "minimal" | "quartet",
//   "difficulty": "faithful" | "standard" | "easier", "key": "Bb" | null,
//   "transpose": null, "seat": "euphonium" | null, "reads": "treble" | "bass" | null,
//   "lead": "lineup" | "seat" | null}`: the SwiftF0 contour of the solo stem (where
// sustained notes end), free-time detection on/off, a fixed BPM for free-time
// passages, the energy gate, beat cleanup, key changes, the lineup, the
// difficulty and a transposition (to a concert key or by semitones). Without stems the
// gate, dynamics and rehearsal marks have nothing to read; see
// [`bc_arrange_layers_band`].
int32_t bc_arrange_layers_song(const uint8_t *const *midi,
                               const uintptr_t *midi_len,
                               const char *beats_text,
                               const char *title,
                               const char *options_json,
                               char **out_composition,
                               char **out_musicxml,
                               char **err);

// Spell MIDI pitches from their context. `request` is JSON
// `{"onsets": [beats...], "pitches": [midi...]}`; writes
// `[{"step": "F", "alter": 1, "octave": 4}, ...]`.
int32_t bc_spell_json(const char *request, char **out, char **err);

// The player's part in a lineup: writes `{"part": "Euphonium" | null, "exact": bool, "same_key": bool}`
// to `*out` for `lineup` ("band", "minimal", "quartet") and `seat` (an id of [`bc_seats`]).
int32_t bc_seat_part(const char *lineup,
                     const char *seat,
                     char **out,
                     char **err);

// Where each part of a Composition's arrangement comes from, in score order: writes
// `[{"part": "Solo Cornet", "source": "your-recording" | "recording" | "arranged"}, ...]` to `*out`.
int32_t bc_part_sources(const char *composition_json,
                        char **out,
                        char **err);

// The seats of the contest band, in score order: writes `[{"id": "2nd-cornet", "name": "2nd Cornet",
// "nb_name": "2. kornett", "instrument": "bb-cornet", "clef": "treble", "reads": ["treble"]}, ...]` to `*out`.
int32_t bc_seats(char **out,
                 char **err);

// Like [`bc_arrange_layers_song`], plus the stems' audio: `wav` and `wav_len`
// hold four WAV files (solo, bass, drums, orchestra; a null pointer = not
// given). Writes one JSON object to `*out`:
// `{"composition": "<composition.json text>", "musicxml": "...",
//   "parts": [{"file_name": "...", "musicxml": "..."}], "separation_check": "<json text>" | null}`.
int32_t bc_arrange_layers_band(const uint8_t *const *midi,
                               const uintptr_t *midi_len,
                               const uint8_t *const *wav,
                               const uintptr_t *wav_len,
                               const char *beats_text,
                               const char *title,
                               const char *options,
                               char **out,
                               char **err);

// Humanize one player's notes. `request` is JSON
// `{"notes": [{"tick", "dur_tick", "start_s", "end_s", "pitch", "velocity"}...],
//   "part": "Solo Cornet", "player": 0, "seed": "brasscribe",
//   "timing": "score" | "performed", "composition": {...} | null}`;
// writes `{"notes": [{"start", "end", "pitch", "velocity", "staccato",
// "from_composition"}...], "detune": cents, "stats": {...}}`.
int32_t bc_humanize_json(const char *request, char **out, char **err);

// Build a talking score from MusicXML and (optionally, may be null) the
// Composition JSON. Writes a handle to `*out`; release with
// [`bc_talking_score_free`].
int32_t bc_talking_score_new(const char *musicxml,
                             const char *composition_json,
                             struct BcTalkingScore **out,
                             char **err);

// Release a talking score. Null is ignored.
void bc_talking_score_free(struct BcTalkingScore *ts);

// The document as JSON (spec §6 shape).
int32_t bc_talking_score_json(const struct BcTalkingScore *ts, char **out, char **err);

// Announce at a cursor. `request`: `{"cursor": {"part", "bar", "event"},
// "context": {"part", "bar", "pitch_mode"}, "settings": {"lang", "pitch_mode",
// "verbosity", "octave_style", "announce_confident"}, "by_bar": false}`.
// Writes `{"text": "...", "context": {...}}`: the announcement and the
// context it leaves behind.
int32_t bc_talking_score_announce(const struct BcTalkingScore *ts,
                                  const char *request,
                                  char **out,
                                  char **err);

// One navigation step. `request`: `{"cursor": {...}, "unit": "note" | "bar" |
// "part" | "uncertain", "forward": true}`. Writes the new cursor as JSON, or
// `null` at either end of the score.
int32_t bc_talking_score_navigate(const struct BcTalkingScore *ts,
                                  const char *request,
                                  char **out,
                                  char **err);

// Export the talking score. `format`: "text" or "html"; `settings_json` may be
// null (defaults).
int32_t bc_talking_score_export(const struct BcTalkingScore *ts,
                                const char *format,
                                const char *settings_json,
                                char **out,
                                char **err);

// Announce one event outside a document (the conformance-vector form):
// `{"part": {...}, "bar": {...}, "event": {...}, "context": {...}, "settings": {...}, "by_bar": false}`.
int32_t bc_talking_announce_json(const char *request,
                                 char **out,
                                 char **err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BRASSCRIBE_H */
