/* brasscribe core C API. Generated by cbindgen from brasscribe-ffi/src/c_api.rs; do not edit. */

#ifndef BRASSCRIBE_H
#define BRASSCRIBE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define BC_OK 0

#define BC_INVALID 1

#define BC_FAILED 2

#define BC_NULL 3

#define BC_PANIC 4

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Release a string returned by this library. Null is ignored.
void bc_string_free(char *s);

// Library version, e.g. "0.1.0". Free with `bc_string_free`.
char *bc_version(void);

// Parse a Composition JSON and write its canonical form to `*out`.
int32_t bc_composition_normalize(const char *json, char **out, char **err);

// Arrange a Composition JSON for brass band and write MusicXML to `*out`.
// `arranger`: "auto", "layers" or "minimal" (null = "auto").
int32_t bc_arrange_musicxml(const char *composition_json,
                            const char *arranger,
                            char **out,
                            char **err);

// Solo-with-band arrangement from six MIDI files (solo SwiftF0, solo
// MuScriptor, solo Basic Pitch, bass, orchestra, drums, in that order) and a
// beat table. Writes the Composition JSON to `*out_composition` and MusicXML
// to `*out_musicxml`. Free time is detected; no solo contour is used.
int32_t bc_arrange_layers_song(const uint8_t *const *midi,
                               const uintptr_t *midi_len,
                               const char *beats_text,
                               const char *title,
                               char **out_composition,
                               char **out_musicxml,
                               char **err);

// Spell MIDI pitches from their context. `request` is JSON
// `{"onsets": [beats...], "pitches": [midi...]}`; writes
// `[{"step": "F", "alter": 1, "octave": 4}, ...]`.
int32_t bc_spell_json(const char *request, char **out, char **err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BRASSCRIBE_H */
