/* scribe core C API. Generated by cbindgen from ffi/src/c_api.rs; do not edit. */

#ifndef SCRIBE_H
#define SCRIBE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define SC_OK 0

#define SC_INVALID 1

#define SC_FAILED 2

#define SC_NULL 3

#define SC_PANIC 4

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Release a string returned by this library. Null is ignored.
void sc_string_free(char *s);

// Library version, e.g. "0.1.0". Free with `sc_string_free`.
char *sc_version(void);

// Parse a Composition JSON and write its canonical form to `*out`.
int32_t sc_composition_normalize(const char *json, char **out, char **err);

// Arrange a Composition JSON for brass band and write MusicXML to `*out`.
// `arranger`: "auto", "layers" or "minimal" (null = "auto").
int32_t sc_arrange_musicxml(const char *composition_json,
                            const char *arranger,
                            char **out,
                            char **err);

// Re-arrange a Composition JSON for a lineup and difficulty and write MusicXML to `*out`.
// `options` may be null (defaults) or
// `{"lineup": "band" | "minimal" | "quartet", "difficulty": "faithful" | "standard" | "easier",
//   "key": "Bb" | null, "transpose": null, "seat": ..., "reads": ..., "lead": ..., "trills": true | false | null}` (the keys of
//   [`sc_arrange_layers_song`]); `transpose`
// is the total from the recording, as in `arrange_musicxml_with`.
int32_t sc_arrange_with(const char *composition_json,
                        const char *options,
                        char **out,
                        char **err);

// Solo-with-band arrangement from six MIDI files (solo SwiftF0, solo
// MuScriptor, solo Basic Pitch, bass, orchestra, drums, in that order) and a
// beat table. Writes the Composition JSON to `*out_composition` and MusicXML
// to `*out_musicxml`.
//
// `options_json` may be null (defaults) or
// `{"solo_contour": {"times": [...], "pitch_hz": [...], "loudness_db": [...]},
//   "free_time": true, "free_tempo": null, "gate": true, "beat_cleanup": true,
//   "key_changes": true, "lineup": "band" | "minimal" | "quartet",
//   "difficulty": "faithful" | "standard" | "easier", "key": "Bb" | null,
//   "transpose": null, "seat": "euphonium" | null, "reads": "treble" | "bass" | null,
//   "lead": "lineup" | "seat" | null, "lang": "en" | "nb" | null}`: the SwiftF0 contour of the solo stem (where
// sustained notes end), free-time detection on/off, a fixed BPM for free-time
// passages, the energy gate, beat cleanup, key changes, the lineup, the
// difficulty, a transposition (to a concert key or by semitones) and the language of the
// arranged parts' footer. Without stems the
// gate, dynamics and rehearsal marks have nothing to read; see
// [`sc_arrange_layers_band`].
int32_t sc_arrange_layers_song(const uint8_t *const *midi,
                               const uintptr_t *midi_len,
                               const char *beats_text,
                               const char *title,
                               const char *options_json,
                               char **out_composition,
                               char **out_musicxml,
                               char **err);

// Spell MIDI pitches from their context. `request` is JSON
// `{"onsets": [beats...], "pitches": [midi...]}`; writes
// `[{"step": "F", "alter": 1, "octave": 4}, ...]`.
int32_t sc_spell_json(const char *request, char **out, char **err);

// The player's part in a lineup: writes `{"part": "Euphonium" | null, "exact": bool, "same_key": bool,
// "takes": "Solo Cornet" | null}`
// to `*out` for `lineup` ("band", "minimal", "quartet") and `seat` (an id of [`sc_seats`]).
int32_t sc_seat_part(const char *lineup,
                     const char *seat,
                     char **out,
                     char **err);

// Where each part of a Composition's arrangement comes from, in score order: writes
// `[{"part": "Solo Cornet", "source": "your-recording" | "recording" | "arranged"}, ...]` to `*out`.
int32_t sc_part_sources(const char *composition_json,
                        char **out,
                        char **err);

// The seats (the contest band's in score order, then the trumpet): writes `[{"id": "2nd-cornet", "name": "2nd Cornet",
// "nb_name": "2. kornett", "instrument": "bb-cornet", "clef": "treble", "reads": ["treble"], "tune": true}, ...]` to `*out`.
int32_t sc_seats(char **out,
                 char **err);

// A part's name in Norwegian (the core's one table): writes the name to `*out`, unchanged when the
// table doesn't know it.
int32_t sc_part_name_nb(const char *name, char **out, char **err);

// Like [`sc_arrange_layers_song`], plus the stems' audio: `wav` and `wav_len`
// hold four WAV files (solo, bass, drums, orchestra; a null pointer = not
// given). Writes one JSON object to `*out`:
// `{"composition": "<composition.json text>", "musicxml": "...",
//   "parts": [{"file_name": "...", "musicxml": "..."}], "separation_check": "<json text>" | null}`.
//
// Every buffer is borrowed for the duration of the call and never copied: the
// stems are read in place while they are decoded.
int32_t sc_arrange_layers_band(const uint8_t *const *midi,
                               const uintptr_t *midi_len,
                               const uint8_t *const *wav,
                               const uintptr_t *wav_len,
                               const char *beats_text,
                               const char *title,
                               const char *options,
                               char **out,
                               char **err);

// [`sc_arrange_layers_band`] with the solo contour as arrays instead of JSON:
// `contour` holds four pointers to `contour_len` doubles each (times in
// seconds, pitch in Hz, loudness in dB, SwiftF0 confidence; a null confidence
// = none), borrowed for the call like the stems. Non-finite values are read
// as the JSON form has them: time 0, pitch 0 Hz (no pitch), loudness −140 dB,
// confidence 0. A null `contour` falls back to `solo_contour` in `options`;
// `contour_len` 0 is an empty contour.
int32_t sc_arrange_layers_band_contour(const uint8_t *const *midi,
                                       const uintptr_t *midi_len,
                                       const uint8_t *const *wav,
                                       const uintptr_t *wav_len,
                                       const double *const *contour,
                                       uintptr_t contour_len,
                                       const char *beats_text,
                                       const char *title,
                                       const char *options,
                                       char **out,
                                       char **err);

// Humanize one player's notes. `request` is JSON
// `{"notes": [{"tick", "dur_tick", "start_s", "end_s", "pitch", "velocity"}...],
//   "part": "Solo Cornet", "player": 0, "seed": "brasscribe",
//   "timing": "score" | "performed", "composition": {...} | null}`;
// writes `{"notes": [{"start", "end", "pitch", "velocity", "staccato",
// "from_composition"}...], "detune": cents, "stats": {...}}`.
int32_t sc_humanize_json(const char *request, char **out, char **err);

// A string and a fret for every note, on a fretted instrument. `request` is `target-fretted`'s
// fingering request:
// `{"instrument": {"preset": "bass-4-standard", "capo": 0}, "notes": [{"pitch", "start", "dur"}...],
//   "options": {"style": "as-played", "tempo_bpm": 96, "pins": [{"note": 0, "string": 2}]}}`;
// writes `{"instrument": {...}, "fingering": {"notes": [{"pitch", "string", "fret", "alternatives",
// "out_of_range", "pinned"}...]}, "violations": [...], "tuning_suggestions": [...]}`.
// See `fretted_fingering_json`.
//
// # Safety
// `request` is null or a NUL-terminated string; `out` and `err` are null or point to a place a
// string pointer can be written. A string written there is released with [`sc_string_free`].
int32_t sc_fretted_fingering_json(const char *request,
                                  char **out,
                                  char **err);

// Tablature as MusicXML. `request` is `target-fretted`'s tab request (the fingering request plus
// `title`, `tempo_bpm`, `meter`, `key`, `tab` and optionally `fingering`); writes
// `{"musicxml": "...", "adjusted_notes": 0}`. See `fretted_tab_json`.
//
// # Safety
// As [`sc_fretted_fingering_json`].
int32_t sc_fretted_tab_json(const char *request, char **out, char **err);

// Tablature as plain text for a monospace font. `request` is the tab request of
// [`sc_fretted_tab_json`], with `"text": {"width": 72}` for the longest line in characters;
// writes the text itself, not JSON. See `fretted_tab_text_json`.
//
// # Safety
// As [`sc_fretted_fingering_json`].
int32_t sc_fretted_tab_text_json(const char *request, char **out, char **err);

// Playing instructions: the tab in words, for a screen reader or a braille display. `request` is
// the tab request of [`sc_fretted_tab_json`], with `"text": {"lang": "en"}` or `"nb"`; writes the
// text itself, not JSON. See `fretted_playing_instructions_json`.
//
// # Safety
// As [`sc_fretted_fingering_json`].
int32_t sc_fretted_playing_instructions_json(const char *request, char **out, char **err);

// Build a talking score from MusicXML and (optionally, may be null) the
// Composition JSON. Writes a handle to `*out`; release with
// [`sc_talking_score_free`].
int32_t sc_talking_score_new(const char *musicxml,
                             const char *composition_json,
                             struct ScTalkingScore **out,
                             char **err);

// Release a talking score. Null is ignored.
void sc_talking_score_free(struct ScTalkingScore *ts);

// The document as JSON (spec §6 shape).
int32_t sc_talking_score_json(const struct ScTalkingScore *ts, char **out, char **err);

// Announce at a cursor. `request`: `{"cursor": {"part", "bar", "event"},
// "context": {"part", "bar", "pitch_mode"}, "settings": {"lang", "pitch_mode",
// "verbosity", "octave_style", "announce_confident"}, "by_bar": false}`.
// Writes `{"text": "...", "context": {...}}`: the announcement and the
// context it leaves behind.
int32_t sc_talking_score_announce(const struct ScTalkingScore *ts,
                                  const char *request,
                                  char **out,
                                  char **err);

// One navigation step. `request`: `{"cursor": {...}, "unit": "note" | "bar" |
// "part" | "uncertain", "forward": true}`. Writes the new cursor as JSON, or
// `null` at either end of the score.
int32_t sc_talking_score_navigate(const struct ScTalkingScore *ts,
                                  const char *request,
                                  char **out,
                                  char **err);

// Export the talking score. `format`: "text" or "html"; `settings_json` may be
// null (defaults).
int32_t sc_talking_score_export(const struct ScTalkingScore *ts,
                                const char *format,
                                const char *settings_json,
                                char **out,
                                char **err);

// Announce one event outside a document (the conformance-vector form):
// `{"part": {...}, "bar": {...}, "event": {...}, "context": {...}, "settings": {...}, "by_bar": false}`.
int32_t sc_talking_announce_json(const char *request,
                                 char **out,
                                 char **err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCRIBE_H */
