"""Upstream Beat This! (small0, PyTorch CPU, minimal postprocessor) references for BeatThisParityTest.

Run with the Beat This adapter environment:
    ml/adapters/beat-this/.venv/bin/python apps/android/pitch/src/test/python/make_beat_this_reference.py [data_dir]

[data_dir] defaults to $BRASSCRIBE_DATA, else the repository's data/.

Writes into src/test/resources:
- beatthis-logmel-reference.json: LogMelSpect of a synthetic 2 s signal (generated by the same formula
  as SyntheticSignals.kt), for the frontend alone.
- beatthis-clicks-reference.json: beats and downbeats of a synthetic 40 s click track.
- beatthis-excerpts-reference.json: beats and downbeats of audio excerpts from data/ (when present);
  the audio itself is not stored, only the file, the span and the result.
"""

import json
import math
import os
import sys
from pathlib import Path

import numpy as np
import soxr
import torch
from beat_this.inference import Audio2Beats
from beat_this.preprocessing import LogMelSpect, load_audio

OUT = Path(__file__).resolve().parents[1] / "resources"
REPO = Path(__file__).resolve().parents[6]
SR = 22050


def sweep(seconds: float = 2.0) -> np.ndarray:
    """Chirp 100 Hz -> 4 kHz plus a 440 Hz tone and a click every 0.25 s (float32)."""
    t = np.arange(int(seconds * SR), dtype=np.float64) / SR
    f0, f1 = 100.0, 4000.0
    k = (f1 - f0) / seconds
    x = 0.3 * np.sin(2 * math.pi * (f0 * t + 0.5 * k * t * t)) + 0.2 * np.sin(2 * math.pi * 440.0 * t)
    idx = np.arange(len(t))
    x[(idx % int(0.25 * SR)) < 20] += 0.5
    return x.astype(np.float32)


def clicks(seconds: float = 40.0, bpm: float = 120.0) -> np.ndarray:
    """Click track: 4/4, the first beat of each bar higher and louder (float32)."""
    n = int(seconds * SR)
    x = np.zeros(n, dtype=np.float64)
    period = 60.0 / bpm
    length = int(0.03 * SR)
    t = np.arange(length, dtype=np.float64) / SR
    env = np.exp(-t / 0.008)
    beat = 0
    while True:
        start = int(round((0.5 + beat * period) * SR))
        if start + length > n:
            break
        accent = beat % 4 == 0
        f = 1500.0 if accent else 1000.0
        a = 0.9 if accent else 0.5
        x[start:start + length] += a * env * np.sin(2 * math.pi * f * t)
        beat += 1
    return x.astype(np.float32)


def main() -> None:
    torch.set_num_threads(1)
    spect = LogMelSpect()
    s = spect(torch.tensor(sweep()))
    (OUT / "beatthis-logmel-reference.json").write_text(json.dumps(
        {"frames": s.shape[0], "mels": s.shape[1], "logmel": [[round(float(v), 6) for v in row] for row in s.numpy()]}))

    tracker = Audio2Beats(checkpoint_path="small0", device="cpu", float16=False, dbn=False)
    b, d = tracker(clicks().astype(np.float64), SR)
    (OUT / "beatthis-clicks-reference.json").write_text(json.dumps(
        {"beats": [float(v) for v in b], "downbeats": [float(v) for v in d]}))

    # The data folder: the first argument, else BRASSCRIBE_DATA, else the repository's data/.
    data = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(os.environ.get("BRASSCRIBE_DATA") or REPO / "data")
    excerpts = []
    for rel, start, end in [("urmp/Dataset/10_March_tpt_sax/AuSep_1_tpt_10_March.wav", 0.0, 30.0),
                            ("mikkel/mikkel.wav", 60.0, 120.0)]:
        path = data / rel
        if not path.exists():
            continue
        signal, sr = load_audio(path)
        if signal.ndim == 2:
            signal = signal.mean(1)
        signal = signal[int(start * sr):int(end * sr)]
        b, d = tracker(signal, sr)
        excerpts.append({"file": rel, "start_s": start, "end_s": end, "beats": [float(v) for v in b],
                         "downbeats": [float(v) for v in d]})
        print(rel, len(b), "beats", len(d), "downbeats")
    (OUT / "beatthis-excerpts-reference.json").write_text(json.dumps({"excerpts": excerpts}))
    print("logmel", tuple(s.shape), "clicks", len(b))


if __name__ == "__main__":
    main()
