package no.brasscribe.play

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import no.brasscribe.play.score.BandSoundMap
import no.brasscribe.play.score.SamePitchTrim
import no.brasscribe.play.score.TimedNote
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/** The Kotlin resolver against sounds/partsound-vectors.json (generated by sounds/partsound.py). */
class BandSoundResolverTest {
    private val sounds = File(System.getProperty("brasscribe.sounds") ?: "../../../sounds")
    private val map = BandSoundMap.parse(File(sounds, "mapping.json").readText())

    @Test
    fun everyVectorResolvesToTheSamePreset() {
        val vectors = Json.parseToJsonElement(File(sounds, "partsound-vectors.json").readText()).jsonObject
            .getValue("vectors").jsonArray
        val failures = mutableListOf<String>()
        for (v in vectors) {
            val o = v.jsonObject
            val name = o.getValue("name").jsonPrimitive.content
            val inst = o["instrument"].takeUnless { it == null || it is JsonNull }?.jsonPrimitive?.content
            val prog = o["program"]?.jsonPrimitive?.intOrNull
            val got = map.resolve(name, inst, prog)
            val want = o["expect"] as? JsonObject
            if (want == null) {
                if (got != null) failures += "$name: want unresolved, got ${got.part}"
                continue
            }
            val ok = got != null && got.part == want.getValue("part").jsonPrimitive.content &&
                got.step == want.getValue("step").jsonPrimitive.content &&
                got.program == want.getValue("program").jsonPrimitive.int &&
                got.bank == want.getValue("bank").jsonPrimitive.int &&
                got.gainDb == want.getValue("channel_gain_db").jsonPrimitive.double &&
                got.percussion == want.getValue("percussion").jsonPrimitive.boolean
            if (!ok) failures += "$name ($inst, $prog): want $want, got $got"
        }
        assertTrue(failures.joinToString("\n"), failures.isEmpty())
        assertTrue(vectors.size > 20)
    }

    @Test
    fun everyLineupPartHasARealInstrument() {
        val lineups = Json.parseToJsonElement(File(sounds, "mapping.json").readText()).jsonObject.getValue("lineups").jsonObject
        for ((lineup, parts) in lineups) {
            if (lineup == "about") continue
            for (p in parts.jsonArray) {
                val s = map.resolve(p.jsonPrimitive.content)
                assertTrue("$lineup/$p unresolved", s != null && s.step == "exact")
                assertTrue("$lineup/$p has no built instrument", s!!.percussion || s.target != null)
            }
        }
    }

    @Test
    fun aNoteOffNeverEndsTheNextNoteOfItsPitch() {
        val notes = listOf(
            TimedNote(0.0, 0.52, 60),  // humanized: lasts past the next onset of the same pitch
            TimedNote(0.5, 1.0, 60),
            TimedNote(0.2, 0.9, 64),   // another pitch overlapping is untouched
            TimedNote(1.0, 1.2, 67), TimedNote(1.004, 1.3, 67),  // unison onsets 4 ms apart: one voice
        )
        val out = SamePitchTrim.trim(notes)
        assertEquals(0.495, out[0]!!.end, 1e-9)
        assertEquals(notes[1], out[1])
        assertEquals(notes[2], out[2])
        assertNull(out[3])
        assertEquals(notes[4], out[4])
    }
}
