// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(brasscribe_ffiFFI)
import brasscribe_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_brasscribe_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_brasscribe_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBrasscribeFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * A note on the tick grid (24 ticks per beat).
 */
public struct GridNote: Equatable, Hashable {
    public var pitch: Int32
    public var start: Int64
    public var end: Int64
    public var confidence: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pitch: Int32, start: Int64, end: Int64, confidence: Double) {
        self.pitch = pitch
        self.start = start
        self.end = end
        self.confidence = confidence
    }

    

    
}

#if compiler(>=6)
extension GridNote: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGridNote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GridNote {
        return
            try GridNote(
                pitch: FfiConverterInt32.read(from: &buf), 
                start: FfiConverterInt64.read(from: &buf), 
                end: FfiConverterInt64.read(from: &buf), 
                confidence: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: GridNote, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.pitch, into: &buf)
        FfiConverterInt64.write(value.start, into: &buf)
        FfiConverterInt64.write(value.end, into: &buf)
        FfiConverterDouble.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGridNote_lift(_ buf: RustBuffer) throws -> GridNote {
    return try FfiConverterTypeGridNote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGridNote_lower(_ value: GridNote) -> RustBuffer {
    return FfiConverterTypeGridNote.lower(value)
}


public struct InstrumentInfo: Equatable, Hashable {
    public var id: String
    public var name: String
    public var shortName: String
    /**
     * Sounding minus written, semitones.
     */
    public var chromatic: Int32
    public var diatonic: Int32
    public var clef: String
    public var proLow: Int32
    public var proHigh: Int32
    public var comfortableLow: Int32
    public var comfortableHigh: Int32
    public var gmProgram: Int32
    public var sound: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, shortName: String, 
        /**
         * Sounding minus written, semitones.
         */chromatic: Int32, diatonic: Int32, clef: String, proLow: Int32, proHigh: Int32, comfortableLow: Int32, comfortableHigh: Int32, gmProgram: Int32, sound: String) {
        self.id = id
        self.name = name
        self.shortName = shortName
        self.chromatic = chromatic
        self.diatonic = diatonic
        self.clef = clef
        self.proLow = proLow
        self.proHigh = proHigh
        self.comfortableLow = comfortableLow
        self.comfortableHigh = comfortableHigh
        self.gmProgram = gmProgram
        self.sound = sound
    }

    

    
}

#if compiler(>=6)
extension InstrumentInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInstrumentInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InstrumentInfo {
        return
            try InstrumentInfo(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                shortName: FfiConverterString.read(from: &buf), 
                chromatic: FfiConverterInt32.read(from: &buf), 
                diatonic: FfiConverterInt32.read(from: &buf), 
                clef: FfiConverterString.read(from: &buf), 
                proLow: FfiConverterInt32.read(from: &buf), 
                proHigh: FfiConverterInt32.read(from: &buf), 
                comfortableLow: FfiConverterInt32.read(from: &buf), 
                comfortableHigh: FfiConverterInt32.read(from: &buf), 
                gmProgram: FfiConverterInt32.read(from: &buf), 
                sound: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: InstrumentInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.shortName, into: &buf)
        FfiConverterInt32.write(value.chromatic, into: &buf)
        FfiConverterInt32.write(value.diatonic, into: &buf)
        FfiConverterString.write(value.clef, into: &buf)
        FfiConverterInt32.write(value.proLow, into: &buf)
        FfiConverterInt32.write(value.proHigh, into: &buf)
        FfiConverterInt32.write(value.comfortableLow, into: &buf)
        FfiConverterInt32.write(value.comfortableHigh, into: &buf)
        FfiConverterInt32.write(value.gmProgram, into: &buf)
        FfiConverterString.write(value.sound, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstrumentInfo_lift(_ buf: RustBuffer) throws -> InstrumentInfo {
    return try FfiConverterTypeInstrumentInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstrumentInfo_lower(_ value: InstrumentInfo) -> RustBuffer {
    return FfiConverterTypeInstrumentInfo.lower(value)
}


public struct KeyEstimate: Equatable, Hashable {
    /**
     * "F", "Dm", ...
     */
    public var name: String
    public var fifths: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * "F", "Dm", ...
         */name: String, fifths: Int32) {
        self.name = name
        self.fifths = fifths
    }

    

    
}

#if compiler(>=6)
extension KeyEstimate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyEstimate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyEstimate {
        return
            try KeyEstimate(
                name: FfiConverterString.read(from: &buf), 
                fifths: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: KeyEstimate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterInt32.write(value.fifths, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyEstimate_lift(_ buf: RustBuffer) throws -> KeyEstimate {
    return try FfiConverterTypeKeyEstimate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyEstimate_lower(_ value: KeyEstimate) -> RustBuffer {
    return FfiConverterTypeKeyEstimate.lower(value)
}


/**
 * Transcribed layers of a recording as MIDI file bytes.
 */
public struct LayerMidi: Equatable, Hashable {
    public var soloSwiftf0: Data
    public var soloMuscriptor: Data
    public var soloBasicPitch: Data
    public var bass: Data
    public var orchestra: Data
    public var drums: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(soloSwiftf0: Data, soloMuscriptor: Data, soloBasicPitch: Data, bass: Data, orchestra: Data, drums: Data) {
        self.soloSwiftf0 = soloSwiftf0
        self.soloMuscriptor = soloMuscriptor
        self.soloBasicPitch = soloBasicPitch
        self.bass = bass
        self.orchestra = orchestra
        self.drums = drums
    }

    

    
}

#if compiler(>=6)
extension LayerMidi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLayerMidi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LayerMidi {
        return
            try LayerMidi(
                soloSwiftf0: FfiConverterData.read(from: &buf), 
                soloMuscriptor: FfiConverterData.read(from: &buf), 
                soloBasicPitch: FfiConverterData.read(from: &buf), 
                bass: FfiConverterData.read(from: &buf), 
                orchestra: FfiConverterData.read(from: &buf), 
                drums: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: LayerMidi, into buf: inout [UInt8]) {
        FfiConverterData.write(value.soloSwiftf0, into: &buf)
        FfiConverterData.write(value.soloMuscriptor, into: &buf)
        FfiConverterData.write(value.soloBasicPitch, into: &buf)
        FfiConverterData.write(value.bass, into: &buf)
        FfiConverterData.write(value.orchestra, into: &buf)
        FfiConverterData.write(value.drums, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLayerMidi_lift(_ buf: RustBuffer) throws -> LayerMidi {
    return try FfiConverterTypeLayerMidi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLayerMidi_lower(_ value: LayerMidi) -> RustBuffer {
    return FfiConverterTypeLayerMidi.lower(value)
}


/**
 * A performed note (seconds).
 */
public struct PerformedNote: Equatable, Hashable {
    public var pitch: Int32
    public var onset: Double
    public var offset: Double
    public var confidence: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pitch: Int32, onset: Double, offset: Double, confidence: Double?) {
        self.pitch = pitch
        self.onset = onset
        self.offset = offset
        self.confidence = confidence
    }

    

    
}

#if compiler(>=6)
extension PerformedNote: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePerformedNote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PerformedNote {
        return
            try PerformedNote(
                pitch: FfiConverterInt32.read(from: &buf), 
                onset: FfiConverterDouble.read(from: &buf), 
                offset: FfiConverterDouble.read(from: &buf), 
                confidence: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: PerformedNote, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.pitch, into: &buf)
        FfiConverterDouble.write(value.onset, into: &buf)
        FfiConverterDouble.write(value.offset, into: &buf)
        FfiConverterOptionDouble.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePerformedNote_lift(_ buf: RustBuffer) throws -> PerformedNote {
    return try FfiConverterTypePerformedNote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePerformedNote_lower(_ value: PerformedNote) -> RustBuffer {
    return FfiConverterTypePerformedNote.lower(value)
}


/**
 * Frame-level pitch contour of the solo stem (SwiftF0).
 */
public struct SoloContour: Equatable, Hashable {
    public var times: [Double]
    public var pitchHz: [Double]
    public var loudnessDb: [Double]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(times: [Double], pitchHz: [Double], loudnessDb: [Double]) {
        self.times = times
        self.pitchHz = pitchHz
        self.loudnessDb = loudnessDb
    }

    

    
}

#if compiler(>=6)
extension SoloContour: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSoloContour: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SoloContour {
        return
            try SoloContour(
                times: FfiConverterSequenceDouble.read(from: &buf), 
                pitchHz: FfiConverterSequenceDouble.read(from: &buf), 
                loudnessDb: FfiConverterSequenceDouble.read(from: &buf)
        )
    }

    public static func write(_ value: SoloContour, into buf: inout [UInt8]) {
        FfiConverterSequenceDouble.write(value.times, into: &buf)
        FfiConverterSequenceDouble.write(value.pitchHz, into: &buf)
        FfiConverterSequenceDouble.write(value.loudnessDb, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSoloContour_lift(_ buf: RustBuffer) throws -> SoloContour {
    return try FfiConverterTypeSoloContour.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSoloContour_lower(_ value: SoloContour) -> RustBuffer {
    return FfiConverterTypeSoloContour.lower(value)
}


/**
 * Composition and MusicXML of one arrangement.
 */
public struct SongOutput: Equatable, Hashable {
    public var compositionJson: String
    public var musicxml: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(compositionJson: String, musicxml: String) {
        self.compositionJson = compositionJson
        self.musicxml = musicxml
    }

    

    
}

#if compiler(>=6)
extension SongOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSongOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SongOutput {
        return
            try SongOutput(
                compositionJson: FfiConverterString.read(from: &buf), 
                musicxml: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SongOutput, into buf: inout [UInt8]) {
        FfiConverterString.write(value.compositionJson, into: &buf)
        FfiConverterString.write(value.musicxml, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSongOutput_lift(_ buf: RustBuffer) throws -> SongOutput {
    return try FfiConverterTypeSongOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSongOutput_lower(_ value: SongOutput) -> RustBuffer {
    return FfiConverterTypeSongOutput.lower(value)
}


public struct SpelledPitch: Equatable, Hashable {
    /**
     * "C".."B"
     */
    public var step: String
    public var alter: Int32
    public var octave: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * "C".."B"
         */step: String, alter: Int32, octave: Int32) {
        self.step = step
        self.alter = alter
        self.octave = octave
    }

    

    
}

#if compiler(>=6)
extension SpelledPitch: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpelledPitch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpelledPitch {
        return
            try SpelledPitch(
                step: FfiConverterString.read(from: &buf), 
                alter: FfiConverterInt32.read(from: &buf), 
                octave: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SpelledPitch, into buf: inout [UInt8]) {
        FfiConverterString.write(value.step, into: &buf)
        FfiConverterInt32.write(value.alter, into: &buf)
        FfiConverterInt32.write(value.octave, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpelledPitch_lift(_ buf: RustBuffer) throws -> SpelledPitch {
    return try FfiConverterTypeSpelledPitch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpelledPitch_lower(_ value: SpelledPitch) -> RustBuffer {
    return FfiConverterTypeSpelledPitch.lower(value)
}


public 
enum CoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Input could not be read (bad JSON, MIDI or beat table).
     */
    case Invalid(reason: String
    )
    /**
     * A pipeline step failed on valid input.
     */
    case Failed(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Invalid(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Failed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Invalid(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Failed(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSoloContour: FfiConverterRustBuffer {
    typealias SwiftType = SoloContour?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSoloContour.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSoloContour.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [Int32]

    public static func write(_ value: [Int32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int32] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]

    public static func write(_ value: [Double], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterDouble.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Double] {
        let len: Int32 = try readInt(&buf)
        var seq = [Double]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterDouble.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGridNote: FfiConverterRustBuffer {
    typealias SwiftType = [GridNote]

    public static func write(_ value: [GridNote], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGridNote.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GridNote] {
        let len: Int32 = try readInt(&buf)
        var seq = [GridNote]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGridNote.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeInstrumentInfo: FfiConverterRustBuffer {
    typealias SwiftType = [InstrumentInfo]

    public static func write(_ value: [InstrumentInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeInstrumentInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [InstrumentInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [InstrumentInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeInstrumentInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePerformedNote: FfiConverterRustBuffer {
    typealias SwiftType = [PerformedNote]

    public static func write(_ value: [PerformedNote], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePerformedNote.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PerformedNote] {
        let len: Int32 = try readInt(&buf)
        var seq = [PerformedNote]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePerformedNote.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSpelledPitch: FfiConverterRustBuffer {
    typealias SwiftType = [SpelledPitch]

    public static func write(_ value: [SpelledPitch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSpelledPitch.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SpelledPitch] {
        let len: Int32 = try readInt(&buf)
        var seq = [SpelledPitch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSpelledPitch.read(from: &buf))
        }
        return seq
    }
}
/**
 * Solo-with-band arrangement from layer transcriptions and a beat table
 * (`time position` per line, position 1 = downbeat).
 */
public func arrangeLayersSong(layers: LayerMidi, beatsText: String, title: String, soloContour: SoloContour?, freeTime: Bool, freeTempo: Double?)throws  -> SongOutput  {
    return try  FfiConverterTypeSongOutput_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_arrange_layers_song(
        FfiConverterTypeLayerMidi_lower(layers),
        FfiConverterString.lower(beatsText),
        FfiConverterString.lower(title),
        FfiConverterOptionTypeSoloContour.lower(soloContour),
        FfiConverterBool.lower(freeTime),
        FfiConverterOptionDouble.lower(freeTempo),uniffiCallStatus
    )
})
}
/**
 * Arrange a Composition for brass band and return MusicXML (written pitch).
 *
 * `arranger`: "layers" (solo with band), "minimal" (minimal band) or "auto"
 * (layers when the voices carry textural layers).
 */
public func arrangeMusicxml(compositionJson: String, arranger: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_arrange_musicxml(
        FfiConverterString.lower(compositionJson),
        FfiConverterString.lower(arranger),uniffiCallStatus
    )
})
}
/**
 * Minimal-band arrangement from melody, optional melody support, bass and harmony transcriptions.
 */
public func arrangeSong(melody: Data, melodySupport: Data?, bass: Data, harmony: [Data], beatsText: String, title: String)throws  -> SongOutput  {
    return try  FfiConverterTypeSongOutput_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_arrange_song(
        FfiConverterData.lower(melody),
        FfiConverterOptionData.lower(melodySupport),
        FfiConverterData.lower(bass),
        FfiConverterSequenceData.lower(harmony),
        FfiConverterString.lower(beatsText),
        FfiConverterString.lower(title),uniffiCallStatus
    )
})
}
/**
 * Beat times at the notated metrical level (doubled when the tracker locked onto half notes).
 */
public func chooseMetricalLevel(beatTimes: [Double], onsets: [Double]) -> [Double]  {
    return try!  FfiConverterSequenceDouble.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_choose_metrical_level(
        FfiConverterSequenceDouble.lower(beatTimes),
        FfiConverterSequenceDouble.lower(onsets),uniffiCallStatus
    )
})
}
/**
 * Version of the core library.
 */
public func coreVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_core_version(uniffiCallStatus
    )
})
}
/**
 * Krumhansl-Kessler key estimate from note durations (beats) and pitches.
 */
public func estimateKey(durationsBeats: [Double], pitches: [Int32]) -> KeyEstimate  {
    return try!  FfiConverterTypeKeyEstimate_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_estimate_key(
        FfiConverterSequenceDouble.lower(durationsBeats),
        FfiConverterSequenceInt32.lower(pitches),uniffiCallStatus
    )
})
}
/**
 * The brass-band instrument table (ranges are sounding MIDI pitches).
 */
public func instruments() -> [InstrumentInfo]  {
    return try!  FfiConverterSequenceTypeInstrumentInfo.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_instruments(uniffiCallStatus
    )
})
}
/**
 * Parse and re-serialise a Composition (the canonical composition.json text).
 */
public func normalizeComposition(json: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_normalize_composition(
        FfiConverterString.lower(json),uniffiCallStatus
    )
})
}
/**
 * Quantize performed notes onto a beat grid; optionally keep one voice and
 * hold notes across gaps up to `fill_gap_ticks` (0 = no gap filling).
 */
public func quantizeNotes(notes: [PerformedNote], beatTimes: [Double], monophonic: Bool, autoLevel: Bool, fillGapTicks: Int64)throws  -> [GridNote]  {
    return try  FfiConverterSequenceTypeGridNote.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_quantize_notes(
        FfiConverterSequenceTypePerformedNote.lower(notes),
        FfiConverterSequenceDouble.lower(beatTimes),
        FfiConverterBool.lower(monophonic),
        FfiConverterBool.lower(autoLevel),
        FfiConverterInt64.lower(fillGapTicks),uniffiCallStatus
    )
})
}
/**
 * Spell MIDI pitches (ps13) from their context; onsets in beats.
 */
public func spellPitches(onsetsBeats: [Double], pitches: [Int32]) -> [SpelledPitch]  {
    return try!  FfiConverterSequenceTypeSpelledPitch.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_brasscribe_ffi_fn_func_spell_pitches(
        FfiConverterSequenceDouble.lower(onsetsBeats),
        FfiConverterSequenceInt32.lower(pitches),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_brasscribe_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_arrange_layers_song() != 55670) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_arrange_musicxml() != 31318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_arrange_song() != 47821) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_choose_metrical_level() != 1449) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_core_version() != 61046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_estimate_key() != 38258) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_instruments() != 47666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_normalize_composition() != 7581) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_quantize_notes() != 61455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brasscribe_ffi_checksum_func_spell_pitches() != 24205) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBrasscribeFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all