// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.brasscribe_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_brasscribe_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_brasscribe_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "brasscribe_ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "brasscribe_ffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }

    internal fun ensureInitialized() = Unit
    external fun uniffi_brasscribe_ffi_checksum_func_arrange_layers_song(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_arrange_musicxml(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_arrange_song(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_choose_metrical_level(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_core_version(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_estimate_key(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_instruments(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_normalize_composition(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_quantize_notes(
    ): Int
    external fun uniffi_brasscribe_ffi_checksum_func_spell_pitches(
    ): Int
    external fun ffi_brasscribe_ffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "brasscribe_ffi"))
        
    }

    internal fun ensureInitialized() = Unit
    external fun uniffi_brasscribe_ffi_fn_func_arrange_layers_song(`layers`: RustBuffer.ByValue,`beatsText`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,`soloContour`: RustBuffer.ByValue,`freeTime`: Byte,`freeTempo`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_arrange_musicxml(`compositionJson`: RustBuffer.ByValue,`arranger`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_arrange_song(`melody`: RustBuffer.ByValue,`melodySupport`: RustBuffer.ByValue,`bass`: RustBuffer.ByValue,`harmony`: RustBuffer.ByValue,`beatsText`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_choose_metrical_level(`beatTimes`: RustBuffer.ByValue,`onsets`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_core_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_estimate_key(`durationsBeats`: RustBuffer.ByValue,`pitches`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_instruments(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_normalize_composition(`json`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_quantize_notes(`notes`: RustBuffer.ByValue,`beatTimes`: RustBuffer.ByValue,`monophonic`: Byte,`autoLevel`: Byte,`fillGapTicks`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_brasscribe_ffi_fn_func_spell_pitches(`onsetsBeats`: RustBuffer.ByValue,`pitches`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_brasscribe_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_brasscribe_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_brasscribe_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_brasscribe_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_brasscribe_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_brasscribe_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_brasscribe_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_brasscribe_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_brasscribe_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_brasscribe_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_brasscribe_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_brasscribe_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_brasscribe_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_brasscribe_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_brasscribe_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_brasscribe_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_brasscribe_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_brasscribe_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if ((lib.uniffi_brasscribe_ffi_checksum_func_arrange_layers_song() and 0xFFFF) != 55670) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_arrange_musicxml() and 0xFFFF) != 31318) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_arrange_song() and 0xFFFF) != 47821) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_choose_metrical_level() and 0xFFFF) != 1449) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_core_version() and 0xFFFF) != 61046) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_estimate_key() and 0xFFFF) != 38258) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_instruments() and 0xFFFF) != 47666) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_normalize_composition() and 0xFFFF) != 7581) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_quantize_notes() and 0xFFFF) != 61455) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_brasscribe_ffi_checksum_func_spell_pitches() and 0xFFFF) != 24205) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    // Call arbitrary methods on IntegrityCheckingUniffiLib and UniffiLib to ensure that
    // their init blocks run. This ensures initialization across crates works as expected.
    IntegrityCheckingUniffiLib.ensureInitialized()
    UniffiLib.ensureInitialized()
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * A note on the tick grid (24 ticks per beat).
 */
data class GridNote (
    var `pitch`: kotlin.Int
    , 
    var `start`: kotlin.Long
    , 
    var `end`: kotlin.Long
    , 
    var `confidence`: kotlin.Double
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeGridNote: FfiConverterRustBuffer<GridNote> {
    override fun read(buf: ByteBuffer): GridNote {
        return GridNote(
            FfiConverterInt.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: GridNote) = (
            FfiConverterInt.allocationSize(value.`pitch`) +
            FfiConverterLong.allocationSize(value.`start`) +
            FfiConverterLong.allocationSize(value.`end`) +
            FfiConverterDouble.allocationSize(value.`confidence`)
    )

    override fun write(value: GridNote, buf: ByteBuffer) {
            FfiConverterInt.write(value.`pitch`, buf)
            FfiConverterLong.write(value.`start`, buf)
            FfiConverterLong.write(value.`end`, buf)
            FfiConverterDouble.write(value.`confidence`, buf)
    }
}



data class InstrumentInfo (
    var `id`: kotlin.String
    , 
    var `name`: kotlin.String
    , 
    var `shortName`: kotlin.String
    , 
    /**
     * Sounding minus written, semitones.
     */
    var `chromatic`: kotlin.Int
    , 
    var `diatonic`: kotlin.Int
    , 
    var `clef`: kotlin.String
    , 
    var `proLow`: kotlin.Int
    , 
    var `proHigh`: kotlin.Int
    , 
    var `comfortableLow`: kotlin.Int
    , 
    var `comfortableHigh`: kotlin.Int
    , 
    var `gmProgram`: kotlin.Int
    , 
    var `sound`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeInstrumentInfo: FfiConverterRustBuffer<InstrumentInfo> {
    override fun read(buf: ByteBuffer): InstrumentInfo {
        return InstrumentInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: InstrumentInfo) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`shortName`) +
            FfiConverterInt.allocationSize(value.`chromatic`) +
            FfiConverterInt.allocationSize(value.`diatonic`) +
            FfiConverterString.allocationSize(value.`clef`) +
            FfiConverterInt.allocationSize(value.`proLow`) +
            FfiConverterInt.allocationSize(value.`proHigh`) +
            FfiConverterInt.allocationSize(value.`comfortableLow`) +
            FfiConverterInt.allocationSize(value.`comfortableHigh`) +
            FfiConverterInt.allocationSize(value.`gmProgram`) +
            FfiConverterString.allocationSize(value.`sound`)
    )

    override fun write(value: InstrumentInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`shortName`, buf)
            FfiConverterInt.write(value.`chromatic`, buf)
            FfiConverterInt.write(value.`diatonic`, buf)
            FfiConverterString.write(value.`clef`, buf)
            FfiConverterInt.write(value.`proLow`, buf)
            FfiConverterInt.write(value.`proHigh`, buf)
            FfiConverterInt.write(value.`comfortableLow`, buf)
            FfiConverterInt.write(value.`comfortableHigh`, buf)
            FfiConverterInt.write(value.`gmProgram`, buf)
            FfiConverterString.write(value.`sound`, buf)
    }
}



data class KeyEstimate (
    /**
     * "F", "Dm", ...
     */
    var `name`: kotlin.String
    , 
    var `fifths`: kotlin.Int
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeKeyEstimate: FfiConverterRustBuffer<KeyEstimate> {
    override fun read(buf: ByteBuffer): KeyEstimate {
        return KeyEstimate(
            FfiConverterString.read(buf),
            FfiConverterInt.read(buf),
        )
    }

    override fun allocationSize(value: KeyEstimate) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterInt.allocationSize(value.`fifths`)
    )

    override fun write(value: KeyEstimate, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterInt.write(value.`fifths`, buf)
    }
}



/**
 * Transcribed layers of a recording as MIDI file bytes.
 */
data class LayerMidi (
    var `soloSwiftf0`: kotlin.ByteArray
    , 
    var `soloMuscriptor`: kotlin.ByteArray
    , 
    var `soloBasicPitch`: kotlin.ByteArray
    , 
    var `bass`: kotlin.ByteArray
    , 
    var `orchestra`: kotlin.ByteArray
    , 
    var `drums`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeLayerMidi: FfiConverterRustBuffer<LayerMidi> {
    override fun read(buf: ByteBuffer): LayerMidi {
        return LayerMidi(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: LayerMidi) = (
            FfiConverterByteArray.allocationSize(value.`soloSwiftf0`) +
            FfiConverterByteArray.allocationSize(value.`soloMuscriptor`) +
            FfiConverterByteArray.allocationSize(value.`soloBasicPitch`) +
            FfiConverterByteArray.allocationSize(value.`bass`) +
            FfiConverterByteArray.allocationSize(value.`orchestra`) +
            FfiConverterByteArray.allocationSize(value.`drums`)
    )

    override fun write(value: LayerMidi, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`soloSwiftf0`, buf)
            FfiConverterByteArray.write(value.`soloMuscriptor`, buf)
            FfiConverterByteArray.write(value.`soloBasicPitch`, buf)
            FfiConverterByteArray.write(value.`bass`, buf)
            FfiConverterByteArray.write(value.`orchestra`, buf)
            FfiConverterByteArray.write(value.`drums`, buf)
    }
}



/**
 * A performed note (seconds).
 */
data class PerformedNote (
    var `pitch`: kotlin.Int
    , 
    var `onset`: kotlin.Double
    , 
    var `offset`: kotlin.Double
    , 
    var `confidence`: kotlin.Double?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePerformedNote: FfiConverterRustBuffer<PerformedNote> {
    override fun read(buf: ByteBuffer): PerformedNote {
        return PerformedNote(
            FfiConverterInt.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
        )
    }

    override fun allocationSize(value: PerformedNote) = (
            FfiConverterInt.allocationSize(value.`pitch`) +
            FfiConverterDouble.allocationSize(value.`onset`) +
            FfiConverterDouble.allocationSize(value.`offset`) +
            FfiConverterOptionalDouble.allocationSize(value.`confidence`)
    )

    override fun write(value: PerformedNote, buf: ByteBuffer) {
            FfiConverterInt.write(value.`pitch`, buf)
            FfiConverterDouble.write(value.`onset`, buf)
            FfiConverterDouble.write(value.`offset`, buf)
            FfiConverterOptionalDouble.write(value.`confidence`, buf)
    }
}



/**
 * Frame-level pitch contour of the solo stem (SwiftF0).
 */
data class SoloContour (
    var `times`: List<kotlin.Double>
    , 
    var `pitchHz`: List<kotlin.Double>
    , 
    var `loudnessDb`: List<kotlin.Double>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSoloContour: FfiConverterRustBuffer<SoloContour> {
    override fun read(buf: ByteBuffer): SoloContour {
        return SoloContour(
            FfiConverterSequenceDouble.read(buf),
            FfiConverterSequenceDouble.read(buf),
            FfiConverterSequenceDouble.read(buf),
        )
    }

    override fun allocationSize(value: SoloContour) = (
            FfiConverterSequenceDouble.allocationSize(value.`times`) +
            FfiConverterSequenceDouble.allocationSize(value.`pitchHz`) +
            FfiConverterSequenceDouble.allocationSize(value.`loudnessDb`)
    )

    override fun write(value: SoloContour, buf: ByteBuffer) {
            FfiConverterSequenceDouble.write(value.`times`, buf)
            FfiConverterSequenceDouble.write(value.`pitchHz`, buf)
            FfiConverterSequenceDouble.write(value.`loudnessDb`, buf)
    }
}



/**
 * Composition and MusicXML of one arrangement.
 */
data class SongOutput (
    var `compositionJson`: kotlin.String
    , 
    var `musicxml`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSongOutput: FfiConverterRustBuffer<SongOutput> {
    override fun read(buf: ByteBuffer): SongOutput {
        return SongOutput(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SongOutput) = (
            FfiConverterString.allocationSize(value.`compositionJson`) +
            FfiConverterString.allocationSize(value.`musicxml`)
    )

    override fun write(value: SongOutput, buf: ByteBuffer) {
            FfiConverterString.write(value.`compositionJson`, buf)
            FfiConverterString.write(value.`musicxml`, buf)
    }
}



data class SpelledPitch (
    /**
     * "C".."B"
     */
    var `step`: kotlin.String
    , 
    var `alter`: kotlin.Int
    , 
    var `octave`: kotlin.Int
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSpelledPitch: FfiConverterRustBuffer<SpelledPitch> {
    override fun read(buf: ByteBuffer): SpelledPitch {
        return SpelledPitch(
            FfiConverterString.read(buf),
            FfiConverterInt.read(buf),
            FfiConverterInt.read(buf),
        )
    }

    override fun allocationSize(value: SpelledPitch) = (
            FfiConverterString.allocationSize(value.`step`) +
            FfiConverterInt.allocationSize(value.`alter`) +
            FfiConverterInt.allocationSize(value.`octave`)
    )

    override fun write(value: SpelledPitch, buf: ByteBuffer) {
            FfiConverterString.write(value.`step`, buf)
            FfiConverterInt.write(value.`alter`, buf)
            FfiConverterInt.write(value.`octave`, buf)
    }
}





sealed class CoreException: kotlin.Exception() {
    
    /**
     * Input could not be read (bad JSON, MIDI or beat table).
     */
    class Invalid(
        
        val `reason`: kotlin.String
        ) : CoreException() {
        override val message
            get() = "reason=${ `reason` }"
    }
    
    /**
     * A pipeline step failed on valid input.
     */
    class Failed(
        
        val `reason`: kotlin.String
        ) : CoreException() {
        override val message
            get() = "reason=${ `reason` }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CoreException> {
        override fun lift(error_buf: RustBuffer.ByValue): CoreException = FfiConverterTypeCoreError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeCoreError : FfiConverterRustBuffer<CoreException> {
    override fun read(buf: ByteBuffer): CoreException {
        

        return when(buf.getInt()) {
            1 -> CoreException.Invalid(
                FfiConverterString.read(buf),
                )
            2 -> CoreException.Failed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CoreException): ULong {
        return when(value) {
            is CoreException.Invalid -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`reason`)
            )
            is CoreException.Failed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`reason`)
            )
        }
    }

    override fun write(value: CoreException, buf: ByteBuffer) {
        when(value) {
            is CoreException.Invalid -> {
                buf.putInt(1)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
            is CoreException.Failed -> {
                buf.putInt(2)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalDouble: FfiConverterRustBuffer<kotlin.Double?> {
    override fun read(buf: ByteBuffer): kotlin.Double? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterDouble.read(buf)
    }

    override fun allocationSize(value: kotlin.Double?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterDouble.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Double?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterDouble.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalByteArray: FfiConverterRustBuffer<kotlin.ByteArray?> {
    override fun read(buf: ByteBuffer): kotlin.ByteArray? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterByteArray.read(buf)
    }

    override fun allocationSize(value: kotlin.ByteArray?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterByteArray.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ByteArray?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterByteArray.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeSoloContour: FfiConverterRustBuffer<SoloContour?> {
    override fun read(buf: ByteBuffer): SoloContour? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeSoloContour.read(buf)
    }

    override fun allocationSize(value: SoloContour?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeSoloContour.allocationSize(value)
        }
    }

    override fun write(value: SoloContour?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeSoloContour.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceInt: FfiConverterRustBuffer<List<kotlin.Int>> {
    override fun read(buf: ByteBuffer): List<kotlin.Int> {
        val len = buf.getInt()
        return List<kotlin.Int>(len) {
            FfiConverterInt.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Int>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterInt.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Int>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterInt.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceDouble: FfiConverterRustBuffer<List<kotlin.Double>> {
    override fun read(buf: ByteBuffer): List<kotlin.Double> {
        val len = buf.getInt()
        return List<kotlin.Double>(len) {
            FfiConverterDouble.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Double>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterDouble.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Double>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterDouble.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceByteArray: FfiConverterRustBuffer<List<kotlin.ByteArray>> {
    override fun read(buf: ByteBuffer): List<kotlin.ByteArray> {
        val len = buf.getInt()
        return List<kotlin.ByteArray>(len) {
            FfiConverterByteArray.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.ByteArray>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterByteArray.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.ByteArray>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterByteArray.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeGridNote: FfiConverterRustBuffer<List<GridNote>> {
    override fun read(buf: ByteBuffer): List<GridNote> {
        val len = buf.getInt()
        return List<GridNote>(len) {
            FfiConverterTypeGridNote.read(buf)
        }
    }

    override fun allocationSize(value: List<GridNote>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeGridNote.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<GridNote>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeGridNote.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeInstrumentInfo: FfiConverterRustBuffer<List<InstrumentInfo>> {
    override fun read(buf: ByteBuffer): List<InstrumentInfo> {
        val len = buf.getInt()
        return List<InstrumentInfo>(len) {
            FfiConverterTypeInstrumentInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<InstrumentInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeInstrumentInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<InstrumentInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeInstrumentInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePerformedNote: FfiConverterRustBuffer<List<PerformedNote>> {
    override fun read(buf: ByteBuffer): List<PerformedNote> {
        val len = buf.getInt()
        return List<PerformedNote>(len) {
            FfiConverterTypePerformedNote.read(buf)
        }
    }

    override fun allocationSize(value: List<PerformedNote>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePerformedNote.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PerformedNote>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePerformedNote.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSpelledPitch: FfiConverterRustBuffer<List<SpelledPitch>> {
    override fun read(buf: ByteBuffer): List<SpelledPitch> {
        val len = buf.getInt()
        return List<SpelledPitch>(len) {
            FfiConverterTypeSpelledPitch.read(buf)
        }
    }

    override fun allocationSize(value: List<SpelledPitch>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSpelledPitch.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<SpelledPitch>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSpelledPitch.write(it, buf)
        }
    }
}
        /**
         * Solo-with-band arrangement from layer transcriptions and a beat table
         * (`time position` per line, position 1 = downbeat).
         */
    @Throws(CoreException::class) fun `arrangeLayersSong`(`layers`: LayerMidi, `beatsText`: kotlin.String, `title`: kotlin.String, `soloContour`: SoloContour?, `freeTime`: kotlin.Boolean, `freeTempo`: kotlin.Double?): SongOutput {
            return FfiConverterTypeSongOutput.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_arrange_layers_song(
    
        
        FfiConverterTypeLayerMidi.lower(`layers`),
        FfiConverterString.lower(`beatsText`),
        FfiConverterString.lower(`title`),
        FfiConverterOptionalTypeSoloContour.lower(`soloContour`),
        FfiConverterBoolean.lower(`freeTime`),
        FfiConverterOptionalDouble.lower(`freeTempo`),_status)
}
    )
    }
    

        /**
         * Arrange a Composition for brass band and return MusicXML (written pitch).
         *
         * `arranger`: "layers" (solo with band), "minimal" (minimal band) or "auto"
         * (layers when the voices carry textural layers).
         */
    @Throws(CoreException::class) fun `arrangeMusicxml`(`compositionJson`: kotlin.String, `arranger`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_arrange_musicxml(
    
        
        FfiConverterString.lower(`compositionJson`),
        FfiConverterString.lower(`arranger`),_status)
}
    )
    }
    

        /**
         * Minimal-band arrangement from melody, optional melody support, bass and harmony transcriptions.
         */
    @Throws(CoreException::class) fun `arrangeSong`(`melody`: kotlin.ByteArray, `melodySupport`: kotlin.ByteArray?, `bass`: kotlin.ByteArray, `harmony`: List<kotlin.ByteArray>, `beatsText`: kotlin.String, `title`: kotlin.String): SongOutput {
            return FfiConverterTypeSongOutput.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_arrange_song(
    
        
        FfiConverterByteArray.lower(`melody`),
        FfiConverterOptionalByteArray.lower(`melodySupport`),
        FfiConverterByteArray.lower(`bass`),
        FfiConverterSequenceByteArray.lower(`harmony`),
        FfiConverterString.lower(`beatsText`),
        FfiConverterString.lower(`title`),_status)
}
    )
    }
    

        /**
         * Beat times at the notated metrical level (doubled when the tracker locked onto half notes).
         */ fun `chooseMetricalLevel`(`beatTimes`: List<kotlin.Double>, `onsets`: List<kotlin.Double>): List<kotlin.Double> {
            return FfiConverterSequenceDouble.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_choose_metrical_level(
    
        
        FfiConverterSequenceDouble.lower(`beatTimes`),
        FfiConverterSequenceDouble.lower(`onsets`),_status)
}
    )
    }
    

        /**
         * Version of the core library.
         */ fun `coreVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_core_version(
    
        _status)
}
    )
    }
    

        /**
         * Krumhansl-Kessler key estimate from note durations (beats) and pitches.
         */ fun `estimateKey`(`durationsBeats`: List<kotlin.Double>, `pitches`: List<kotlin.Int>): KeyEstimate {
            return FfiConverterTypeKeyEstimate.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_estimate_key(
    
        
        FfiConverterSequenceDouble.lower(`durationsBeats`),
        FfiConverterSequenceInt.lower(`pitches`),_status)
}
    )
    }
    

        /**
         * The brass-band instrument table (ranges are sounding MIDI pitches).
         */ fun `instruments`(): List<InstrumentInfo> {
            return FfiConverterSequenceTypeInstrumentInfo.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_instruments(
    
        _status)
}
    )
    }
    

        /**
         * Parse and re-serialise a Composition (the canonical composition.json text).
         */
    @Throws(CoreException::class) fun `normalizeComposition`(`json`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_normalize_composition(
    
        
        FfiConverterString.lower(`json`),_status)
}
    )
    }
    

        /**
         * Quantize performed notes onto a beat grid; optionally keep one voice and
         * hold notes across gaps up to `fill_gap_ticks` (0 = no gap filling).
         */
    @Throws(CoreException::class) fun `quantizeNotes`(`notes`: List<PerformedNote>, `beatTimes`: List<kotlin.Double>, `monophonic`: kotlin.Boolean, `autoLevel`: kotlin.Boolean, `fillGapTicks`: kotlin.Long): List<GridNote> {
            return FfiConverterSequenceTypeGridNote.lift(
    uniffiRustCallWithError(CoreException) { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_quantize_notes(
    
        
        FfiConverterSequenceTypePerformedNote.lower(`notes`),
        FfiConverterSequenceDouble.lower(`beatTimes`),
        FfiConverterBoolean.lower(`monophonic`),
        FfiConverterBoolean.lower(`autoLevel`),
        FfiConverterLong.lower(`fillGapTicks`),_status)
}
    )
    }
    

        /**
         * Spell MIDI pitches (ps13) from their context; onsets in beats.
         */ fun `spellPitches`(`onsetsBeats`: List<kotlin.Double>, `pitches`: List<kotlin.Int>): List<SpelledPitch> {
            return FfiConverterSequenceTypeSpelledPitch.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_brasscribe_ffi_fn_func_spell_pitches(
    
        
        FfiConverterSequenceDouble.lower(`onsetsBeats`),
        FfiConverterSequenceInt.lower(`pitches`),_status)
}
    )
    }
    


