# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate platform code from the Brasscribe design tokens.

    uv run design/tokens/build.py          # write every output
    uv run design/tokens/build.py --check  # exit 1 if any output is missing or out of date (CI)

Inputs:  design/tokens/tokens.json (DTCG), design/tokens/icons.json, design/brand/icons/**,
         design/brand/fonts/*
Outputs: design/dist/apple/      BrasscribeDesign.xcassets, BrasscribeDesign.swift, Fonts/
         design/dist/android/    kotlin/no/brasscribe/design/*.kt, res/drawable/ic_bc_*.xml, res/font/
         design/dist/windows/    BrasscribeTheme.xaml, BrasscribePinkTheme.xaml, Assets/Fonts/
         design/dist/web/        brasscribe.css, fonts.css, studio-compat.css, icons/*.svg, fonts/
         design/dist/icon-map.md
         docs/accessibility/design-tokens.json (the accessibility palette, kept in its existing shape)

Every output is a pure function of the inputs: no timestamps, sorted where order is free.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DIST = ROOT / "design" / "dist"
BRAND = ROOT / "design" / "brand"
TOKENS = json.loads((HERE / "tokens.json").read_text())
ICONS = json.loads((HERE / "icons.json").read_text())["actions"]
EXT = TOKENS["$extensions"]["no.brasscribe"]
MODES = EXT["modes"]
HEADER = "Generated by design/tokens/build.py from design/tokens/tokens.json. Do not edit."
# The accessibility palette (docs/accessibility/design-tokens.json) keeps its three themes;
# qa/reports/contrast-design-tokens.md checks every mode, high-contrast-light included.
A11Y_MODES = ("light", "dark", "high-contrast")


# ---------------------------------------------------------------- helpers

def roles() -> list[str]:
    return [k for k in TOKENS["color"]["light"] if not k.startswith("$")]


def hexval(mode: str, role: str) -> str:
    return TOKENS["color"][mode][role]["$value"]["hex"]


def alpha(mode: str, role: str) -> float:
    return TOKENS["color"][mode][role]["$value"].get("alpha", 1.0)


def desc(role: str) -> str:
    return TOKENS["color"]["light"][role].get("$description", "")


def camel(name: str) -> str:
    parts = re.split(r"[-_ ]", name)
    out = parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return ("n" + out) if out[:1].isdigit() else out


def pascal(name: str) -> str:
    c = camel(name)
    return c[:1].upper() + c[1:]


def upper_snake(name: str) -> str:
    return re.sub(r"[-\s]", "_", name).upper()


def dimension(tok: dict) -> float:
    return tok["$value"]["value"]


def fmt(v: float) -> str:
    return f"{v:g}"


def group(path: str) -> dict:
    node = TOKENS
    for p in path.split("."):
        node = node[p]
    return {k: v for k, v in node.items() if not k.startswith("$")}


def rgb_components(h: str) -> tuple[str, str, str]:
    return tuple(f"{int(h[i:i + 2], 16) / 255:.3f}" for i in (1, 3, 5))  # type: ignore[return-value]


def transform_path(d: str, s: float, tx: float, ty: float) -> str:
    """Scale then translate an SVG path (M L H V Q T C S Z, absolute and relative)."""
    toks = re.findall(r"[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?", d)
    arity = {"M": 2, "L": 2, "H": 1, "V": 1, "Q": 4, "T": 2, "C": 6, "S": 4, "Z": 0}
    out, i, cmd = [], 0, "M"
    while i < len(toks):
        t = toks[i]
        if t.isalpha():
            cmd = t
            out.append(t)
            i += 1
            if cmd in "Zz":
                continue
        n = arity[cmd.upper()]
        vals = [float(v) for v in toks[i:i + n]]
        i += n
        if cmd.isupper():
            if cmd == "H":
                vals = [vals[0] * s + tx]
            elif cmd == "V":
                vals = [vals[0] * s + ty]
            else:
                vals = [v * s + (tx if k % 2 == 0 else ty) for k, v in enumerate(vals)]
        else:
            vals = [v * s for v in vals]
        out.append(" ".join(f"{round(v, 3):g}" for v in vals))
    return " ".join(out)


def svg_path(file: Path) -> str:
    return " ".join(re.findall(r'<path[^>]*\sd="([^"]+)"', file.read_text()))


def icon_source(action: str, platform: str) -> tuple[str, str]:
    """Return ('system', name) or ('svg', path d on the 960 grid) for an action on a platform."""
    v = ICONS[action][platform]
    if isinstance(v, dict) and "custom" in v:
        return "svg", svg_path(BRAND / "icons" / "custom" / f"{v['custom']}.svg")
    if platform == "material":
        return "svg", svg_path(BRAND / "icons" / "material" / f"{v}.svg")
    return "system", v


# ---------------------------------------------------------------- accessibility compat file

def a11y_json() -> str:
    compat = EXT["a11yCompat"]
    keys = compat["keys"]
    pairs = [p for p in EXT["contrast"]["pairs"] if p[0] in keys and p[1] in keys]
    dist = [p for p in EXT["contrast"]["distinguish"] if p[0] in keys and p[1] in keys]
    data = {
        "$comment": ("Colour tokens for Play and Studio. Generated by design/tokens/build.py from "
                     "design/tokens/tokens.json, which is the source; edit that file. Checked by "
                     "qa/tools/contrast.py; the generated report is qa/reports/contrast-tokens.md. "
                     "Pairs list [foreground, background, minimum ratio, WCAG criterion]."),
        "themes": {m: {k: hexval(m, k) for k in keys} for m in A11Y_MODES},
        "pairs": pairs,
        "distinguish": dist,
        "legacy": {"$comment": "Colour used by the current engine output for SwiftF0-only notes; checked for reference.",
                   **compat["legacy"]},
    }
    # Same layout as the hand-written file: one pair per line.
    text = json.dumps(data, indent=2, ensure_ascii=False)
    for key in ("pairs", "distinguish"):
        rows = ",\n".join("    " + json.dumps(p, ensure_ascii=False).replace(",", ", ").replace(",  ", ", ") for p in data[key])
        block = json.dumps(data[key], indent=2, ensure_ascii=False).replace("\n", "\n  ")
        text = text.replace(f'"{key}": {block}', f'"{key}": [\n{rows}\n  ]')
    return text + "\n"


# ---------------------------------------------------------------- Apple

def apple_outputs() -> dict[str, str | bytes]:
    out: dict[str, str | bytes] = {}
    base = "apple/BrasscribeDesign.xcassets"
    info = {"info": {"author": "xcode", "version": 1}}
    out[f"{base}/Contents.json"] = json.dumps(info, indent=2) + "\n"
    out[f"{base}/Brasscribe/Contents.json"] = json.dumps(
        {"info": {"author": "xcode", "version": 1}, "properties": {"provides-namespace": True}}, indent=2) + "\n"

    def entry(mode: str, role: str, appearances: list[dict]) -> dict:
        r, g, b = rgb_components(hexval(mode, role))
        e = {"color": {"color-space": "srgb", "components": {
            "alpha": f"{alpha(mode, role):.3f}", "red": r, "green": g, "blue": b}}, "idiom": "universal"}
        if appearances:
            e["appearances"] = appearances
        return e

    dark = {"appearance": "luminosity", "value": "dark"}
    high = {"appearance": "contrast", "value": "high"}
    # The hidden Pink palette has its own namespace with the same high-contrast appearances, so Increase
    # Contrast still wins over it.
    out[f"{base}/BrasscribePink/Contents.json"] = out[f"{base}/Brasscribe/Contents.json"]
    for role in roles():
        for ns, light, dk in (("Brasscribe", "light", "dark"), ("BrasscribePink", "pink", "pink-dark")):
            colors = [entry(light, role, []), entry(dk, role, [dark]),
                      entry("high-contrast", role, [high]), entry("high-contrast", role, [dark, high])]
            out[f"{base}/{ns}/{camel(role)}.colorset/Contents.json"] = json.dumps(
                {"colors": colors, "info": {"author": "xcode", "version": 1}}, indent=2) + "\n"

    lines = [f"// {HEADER}", "//", "// Add BrasscribeDesign.xcassets and Fonts/InstrumentSerif-Regular.ttf to the same target",
             "// as this file, and list the font under UIAppFonts (iOS) / ATSApplicationFontsPath (macOS).", "",
             "import SwiftUI", "",
             "public enum BrasscribeDesign {",
             "    private final class BundleToken {}",
             "    /// The bundle that holds BrasscribeDesign.xcassets: the package resources or the target this file is in.",
             "    public static let bundle: Bundle = {",
             "        #if SWIFT_PACKAGE",
             "        return Bundle.module",
             "        #else",
             "        return Bundle(for: BundleToken.self)",
             "        #endif",
             "    }()", ""]

    lines += ["    /// Spacing on the 4/8 grid, in points."]
    lines += ["    public enum Space {"]
    for k, v in group("space").items():
        lines.append(f"        public static let s{k}: CGFloat = {fmt(dimension(v))}")
    lines += ["    }", "", "    /// Corner radii, in points. `md` is the button shape on every platform.", "    public enum Radius {"]
    for k, v in group("radius").items():
        lines.append(f"        public static let {camel(k)}: CGFloat = {fmt(dimension(v))}")
    lines += ["    }", "", "    public enum Size {",
              f"        public static let touchMin: CGFloat = {fmt(dimension(TOKENS['size']['touch-min-apple']))}",
              f"        public static let iconSmall: CGFloat = {fmt(dimension(TOKENS['size']['icon-sm']))}",
              f"        public static let iconMedium: CGFloat = {fmt(dimension(TOKENS['size']['icon-md']))}",
              f"        public static let iconLarge: CGFloat = {fmt(dimension(TOKENS['size']['icon-lg']))}",
              f"        public static let contentMaxWidth: CGFloat = {fmt(dimension(TOKENS['size']['content-max']))}",
              f"        public static let sidebarWidth: CGFloat = {fmt(dimension(TOKENS['size']['sidebar']))}",
              "    }", ""]
    sc = TOKENS["score"]
    lines += ["    /// Score-view metrics. Colours are in Color.Brasscribe.", "    public enum Score {"]
    for k in ("cursor-width", "focus-width", "focus-gap", "loop-edge-width", "selection-edge-width"):
        lines.append(f"        public static let {camel(k)}: CGFloat = {fmt(dimension(sc[k]))}")
    for k in ("zoom-min", "zoom-max", "zoom-step", "single-part-reflow-zoom", "mark-size-staff-spaces", "staff-height-min-phone-mm"):
        lines.append(f"        public static let {camel(k)}: Double = {fmt(sc[k]['$value'])}")
    lines += ["    }", ""]
    md = TOKENS["motion"]["duration"]
    ez = TOKENS["motion"]["easing"]
    lines += ["    /// Motion. Every animation goes through `animation(_:reduceMotion:)`.", "    public enum Motion {"]
    for k, v in md.items():
        lines.append(f"        public static let {camel(k)}: Double = {fmt(v['$value']['value'] / 1000)}")
    std = ez["standard"]["$value"]
    lines += [
        "",
        "        /// The standard curve, or a short cross-fade when Reduce Motion is on (nil for instant changes).",
        "        public static func animation(_ duration: Double = base, reduceMotion: Bool) -> Animation? {",
        "            if reduceMotion { return duration == 0 ? nil : .easeInOut(duration: min(duration, reduced)) }",
        f"            return .timingCurve({', '.join(fmt(x) for x in std)}, duration: duration)",
        "        }",
        "    }",
        "}", ""]

    lines += ["/// Which palette `Color.Brasscribe` reads: the standard one, or the hidden Pink one (design/system.md §10).",
              "/// It is observable, so a view that reads a colour in `body` redraws when the palette changes. Light or",
              "/// dark still follows the colour scheme, and Increase Contrast still gives the high-contrast colours.",
              "@Observable",
              "public final class BrasscribePalette: @unchecked Sendable {",
              "    public static let shared = BrasscribePalette()",
              "    public var isPink = false",
              "    public init() {}",
              "}", "",
              "public extension Color {", "    /// Semantic colours with light, dark and high-contrast variants from the asset catalog.",
              "    enum Brasscribe {",
              "        private static func named(_ role: String) -> Color {",
              '            Color((BrasscribePalette.shared.isPink ? "BrasscribePink/" : "Brasscribe/") + role, bundle: BrasscribeDesign.bundle)',
              "        }", ""]
    for role in roles():
        lines.append(f"        /// {desc(role)}")
        lines.append(f'        public static var {camel(role)}: Color {{ named("{camel(role)}") }}')
    lines += ["    }", "}", ""]

    typo = group("typography")
    weight = {400: "regular", 500: "medium", 600: "semibold", 700: "bold"}
    lines += ["public extension Font {", "    /// The type ramp, built on Dynamic Type text styles so it scales with the user's text size.",
              "    enum Brasscribe {"]
    for k, v in typo.items():
        plat = v.get("$extensions", {}).get("no.brasscribe.platform")
        if not plat:
            continue
        style = plat["apple"]["textStyle"]
        w = weight[v["$value"]["fontWeight"]]
        if "display" in v["$value"]["fontFamily"]:
            size = fmt(v["$value"]["fontSize"]["value"])
            expr = f'.custom("InstrumentSerif-Regular", size: {size}, relativeTo: .{style})'
        else:
            expr = f".{style}" + ("" if w == "regular" else f".weight(.{w})")
            if k == "numeric":
                expr += ".monospacedDigit()"
        lines.append(f"        /// {v.get('$description', '')}")
        lines.append(f"        public static let {camel(k)}: Font = {expr}")
    lines += ["    }", "}", ""]

    lines += ["/// One SF Symbol per action. The label is the visible text and the accessible name.",
              "public enum BrasscribeIcon: CaseIterable, Sendable {"]
    for a in ICONS:
        lines.append(f"    case {camel(a)}")
    lines += ["", "    public var systemName: String {", "        switch self {"]
    for a, v in ICONS.items():
        lines.append(f'        case .{camel(a)}: "{v["apple"]}"')
    lines += ["        }", "    }", "}", ""]
    out["apple/BrasscribeDesign.swift"] = "\n".join(lines)
    out["apple/Fonts/InstrumentSerif-Regular.ttf"] = (BRAND / "fonts" / "InstrumentSerif-Regular.ttf").read_bytes()
    out["apple/Fonts/OFL.txt"] = (BRAND / "fonts" / "OFL.txt").read_bytes()
    return out


# ---------------------------------------------------------------- Android

def argb(h: str, a: float = 1.0) -> str:
    return f"0x{round(a * 255):02X}{h[1:].upper()}"


def android_outputs() -> dict[str, str | bytes]:
    out: dict[str, str | bytes] = {}
    pkg = "no.brasscribe.design"
    rs = roles()
    L = [f"// {HEADER}", f"package {pkg}", "",
         "import android.app.UiModeManager",
         "import android.os.Build",
         "import androidx.compose.animation.core.CubicBezierEasing",
         "import androidx.compose.foundation.isSystemInDarkTheme",
         "import androidx.compose.foundation.shape.RoundedCornerShape",
         "import androidx.compose.material3.ColorScheme",
         "import androidx.compose.material3.MaterialTheme",
         "import androidx.compose.material3.Shapes",
         "import androidx.compose.material3.Typography",
         "import androidx.compose.material3.darkColorScheme",
         "import androidx.compose.material3.lightColorScheme",
         "import androidx.compose.runtime.Composable",
         "import androidx.compose.runtime.CompositionLocalProvider",
         "import androidx.compose.runtime.Immutable",
         "import androidx.compose.runtime.ReadOnlyComposable",
         "import androidx.compose.runtime.staticCompositionLocalOf",
         "import androidx.compose.ui.graphics.Color",
         "import androidx.compose.ui.platform.LocalContext",
         "import androidx.compose.ui.text.TextStyle",
         "import androidx.compose.ui.text.font.FontFamily",
         "import androidx.compose.ui.text.font.FontWeight",
         "import androidx.compose.ui.text.style.TextAlign",
         "import androidx.compose.ui.unit.dp",
         "import androidx.compose.ui.unit.sp", "",
         "/** Semantic colours. Material components read [ColorScheme]; the score view reads these directly. */",
         "@Immutable",
         "data class BrasscribeColors("]
    for r in rs:
        L.append(f"    /** {desc(r)} */")
        L.append(f"    val {camel(r)}: Color,")
    L += ["    val isHighContrast: Boolean,", ")", ""]
    for mode, name in (("light", "BrasscribeLightColors"), ("dark", "BrasscribeDarkColors"),
                       ("high-contrast", "BrasscribeHighContrastColors"), ("high-contrast-light", "BrasscribeHighContrastLightColors"),
                       ("pink", "BrasscribePinkColors"), ("pink-dark", "BrasscribePinkDarkColors")):
        if mode == "high-contrast-light":
            L.append("/** High contrast on a light ground. Not yet chosen by [BrasscribeTheme], which uses the dark one. */")
        if mode == "pink":
            L.append("/** The hidden Pink palette (design/system.md §10), chosen by [BrasscribeTheme] with `pink = true`. */")
        L.append(f"val {name} = BrasscribeColors(")
        for r in rs:
            L.append(f"    {camel(r)} = Color({argb(hexval(mode, r), alpha(mode, r))}),")
        L += [f"    isHighContrast = {'true' if mode.startswith('high-contrast') else 'false'},", ")", ""]

    L += ["/** Maps the semantic roles onto Material 3 so stock components look like Brasscribe. */",
          "fun BrasscribeColors.toColorScheme(dark: Boolean): ColorScheme {",
          "    val scheme = if (dark) darkColorScheme() else lightColorScheme()",
          "    return scheme.copy(",
          "        primary = primary, onPrimary = onPrimary,",
          "        primaryContainer = secondary, onPrimaryContainer = onSecondary, inversePrimary = brass,",
          "        secondary = text, onSecondary = bg,",
          "        secondaryContainer = secondary, onSecondaryContainer = onSecondary,",
          "        tertiary = brassText, onTertiary = onPrimary,",
          "        tertiaryContainer = brassTint, onTertiaryContainer = text,",
          "        background = bg, onBackground = text,",
          "        surface = bg, onSurface = text, surfaceVariant = surface, onSurfaceVariant = textMuted,",
          "        surfaceTint = bg, inverseSurface = text, inverseOnSurface = bg,",
          "        error = error, onError = bg, errorContainer = surface, onErrorContainer = error,",
          "        outline = borderStrong, outlineVariant = border, scrim = Color.Black,",
          "        surfaceBright = surfaceRaised, surfaceDim = surface,",
          "        surfaceContainerLowest = surfaceRaised, surfaceContainerLow = surfaceRaised,",
          "        surfaceContainer = surface, surfaceContainerHigh = surfaceRaised, surfaceContainerHighest = secondary,",
          "    )",
          "}", ""]

    typo = group("typography")
    weight = {400: "Normal", 500: "Medium", 600: "SemiBold", 700: "Bold"}
    L += ["/** The type ramp as Material 3 roles. Sizes are sp, so they follow the system font scale. */",
          "fun brasscribeTypography(display: FontFamily = FontFamily.Serif): Typography {",
          "    val base = Typography()", "    return base.copy("]
    used = {}
    for k, v in typo.items():
        plat = v.get("$extensions", {}).get("no.brasscribe.platform")
        if not plat or k == "numeric":
            continue
        m = plat["material"]
        used[m["role"]] = (k, v, m)
    for role, (k, v, m) in used.items():
        fam = "display" if "display" in v["$value"]["fontFamily"] else "FontFamily.Default"
        ls = v["$value"]["letterSpacing"]["value"]
        L.append(f"        {role} = base.{role}.copy(fontFamily = {fam}, fontWeight = FontWeight.{weight[v['$value']['fontWeight']]}, "
                 f"fontSize = {fmt(m['sizeSp'])}.sp, lineHeight = {fmt(m['lineHeightSp'])}.sp, letterSpacing = {fmt(ls)}.sp),")
    L += ["    )", "}", ""]
    num = typo["numeric"]["$extensions"]["no.brasscribe.platform"]["material"]
    L += ["/** Bar/beat, speed and tempo readouts: tabular figures so the numbers don't jiggle. */",
          f"val BrasscribeNumericStyle = TextStyle(fontWeight = FontWeight.Medium, fontSize = {num['sizeSp']}.sp, "
          f"lineHeight = {num['lineHeightSp']}.sp, fontFeatureSettings = \"tnum\", textAlign = TextAlign.Start)", ""]

    rad = group("radius")
    L += ["val BrasscribeShapes = Shapes(",
          f"    extraSmall = RoundedCornerShape({fmt(dimension(rad['xs']))}.dp),",
          f"    small = RoundedCornerShape({fmt(dimension(rad['sm']))}.dp),",
          f"    medium = RoundedCornerShape({fmt(dimension(rad['md']))}.dp),",
          f"    large = RoundedCornerShape({fmt(dimension(rad['lg']))}.dp),",
          f"    extraLarge = RoundedCornerShape({fmt(dimension(rad['xl']))}.dp),",
          ")", "",
          "/** The brand's one button shape. Material buttons default to a pill; pass this instead. */",
          f"val BrasscribeButtonShape = RoundedCornerShape({fmt(dimension(rad['md']))}.dp)", ""]

    L += ["object BrasscribeSpace {"]
    for k, v in group("space").items():
        L.append(f"    val s{k} = {fmt(dimension(v))}.dp")
    L += ["}", "", "object BrasscribeSize {",
          f"    val touchMin = {fmt(dimension(TOKENS['size']['touch-min-android']))}.dp",
          f"    val iconMedium = {fmt(dimension(TOKENS['size']['icon-md']))}.dp",
          f"    val iconLarge = {fmt(dimension(TOKENS['size']['icon-lg']))}.dp",
          f"    val contentMaxWidth = {fmt(dimension(TOKENS['size']['content-max']))}.dp",
          f"    val sidebarWidth = {fmt(dimension(TOKENS['size']['sidebar']))}.dp",
          "}", ""]
    sc = TOKENS["score"]
    L += ["object BrasscribeScore {"]
    for k in ("cursor-width", "focus-width", "focus-gap", "loop-edge-width", "selection-edge-width"):
        L.append(f"    val {camel(k)} = {fmt(dimension(sc[k]))}.dp")
    for k in ("zoom-min", "zoom-max", "zoom-step", "single-part-reflow-zoom"):
        L.append(f"    const val {camel(k)} = {int(sc[k]['$value'])}")
    L += ["}", ""]
    L += ["/** Durations in ms. With animations off (ANIMATOR_DURATION_SCALE 0) use [reduced] cross-fades or none. */",
          "object BrasscribeMotion {"]
    for k, v in TOKENS["motion"]["duration"].items():
        L.append(f"    const val {camel(k)} = {v['$value']['value']}")
    for k, v in TOKENS["motion"]["easing"].items():
        L.append(f"    val {camel(k)}Easing = CubicBezierEasing({', '.join(fmt(x) + 'f' for x in v['$value'])})")
    L += ["}", ""]

    L += ["val LocalBrasscribeColors = staticCompositionLocalOf { BrasscribeLightColors }", "",
          "/** Android 14+ reports the system contrast level; 0.5 and above is treated as high contrast. */",
          "@Composable",
          "fun systemHighContrast(): Boolean {",
          "    val context = LocalContext.current",
          "    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.UPSIDE_DOWN_CAKE) return false",
          "    val ui = context.getSystemService(UiModeManager::class.java) ?: return false",
          "    return ui.contrast >= 0.5f",
          "}", "",
          "/**",
          " * Brasscribe on Material 3. Dynamic colour is deliberately not used: the score palette is",
          " * fixed for accessibility and the brand stays the same on every device.",
          " *",
          " * @param display the brand display face; pass FontFamily(Font(R.font.instrument_serif)) after copying",
          " *   design/dist/android/res/font into the app. Defaults to the system serif.",
          " * @param pink the hidden Pink palette, light or dark by [dark]. The system's high contrast still wins.",
          " */",
          "@Composable",
          "fun BrasscribeTheme(",
          "    dark: Boolean = isSystemInDarkTheme(),",
          "    highContrast: Boolean = systemHighContrast(),",
          "    pink: Boolean = false,",
          "    display: FontFamily = FontFamily.Serif,",
          "    content: @Composable () -> Unit,",
          ") {",
          "    val colors = when {",
          "        highContrast -> BrasscribeHighContrastColors",
          "        pink && dark -> BrasscribePinkDarkColors",
          "        pink -> BrasscribePinkColors",
          "        dark -> BrasscribeDarkColors",
          "        else -> BrasscribeLightColors",
          "    }",
          "    CompositionLocalProvider(LocalBrasscribeColors provides colors) {",
          "        MaterialTheme(",
          "            colorScheme = colors.toColorScheme(dark = dark || highContrast),",
          "            typography = brasscribeTypography(display),",
          "            shapes = BrasscribeShapes,",
          "            content = content,",
          "        )",
          "    }",
          "}", "",
          "object BrasscribeTheme {",
          "    val colors: BrasscribeColors",
          "        @Composable @ReadOnlyComposable get() = LocalBrasscribeColors.current",
          "}", ""]
    out["android/kotlin/no/brasscribe/design/BrasscribeTheme.kt"] = "\n".join(L)

    I = [f"// {HEADER}", f"package {pkg}", "",
         "/**",
         " * One icon per action. Copy design/dist/android/res/drawable/ic_bc_*.xml into the app and use",
         " * painterResource(R.drawable.<drawable>). [material] names the Material Symbols Rounded source",
         " * (or \"custom\"). The label string is the accessible name; see icons.json for en and nb.",
         " */",
         "enum class BrasscribeIcon(val drawable: String, val material: String) {"]
    for a, v in ICONS.items():
        m = v["material"]
        src = m if isinstance(m, str) else "custom:" + m["custom"]
        I.append(f'    {upper_snake(a)}("ic_bc_{a.replace("-", "_")}", "{src}"),')
    I += ["}", ""]
    out["android/kotlin/no/brasscribe/design/BrasscribeIcon.kt"] = "\n".join(I)

    for a in ICONS:
        _, d = icon_source(a, "material")
        out[f"android/res/drawable/ic_bc_{a.replace('-', '_')}.xml"] = (
            '<?xml version="1.0" encoding="utf-8"?>\n'
            f"<!-- {HEADER} -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="24dp" android:height="24dp"\n'
            '    android:viewportWidth="960" android:viewportHeight="960">\n'
            '    <group android:translateY="960">\n'
            f'        <path android:fillColor="#FF000000" android:pathData="{d}"/>\n'
            "    </group>\n</vector>\n")
    out["android/res/font/instrument_serif.ttf"] = (BRAND / "fonts" / "InstrumentSerif-Regular.ttf").read_bytes()
    out["android/res/font/OFL.txt"] = (BRAND / "fonts" / "OFL.txt").read_bytes()
    return out


# ---------------------------------------------------------------- Windows

HC_SYSTEM = {  # role -> WinUI system colour in contrast themes (visual-design-tokens.md §3)
    "bg": "SystemColorWindowColor", "surface": "SystemColorWindowColor", "surface-raised": "SystemColorWindowColor",
    "text": "SystemColorWindowTextColor", "text-muted": "SystemColorWindowTextColor",
    "border": "SystemColorWindowTextColor", "border-strong": "SystemColorWindowTextColor",
    "primary": "SystemColorHighlightColor", "on-primary": "SystemColorHighlightTextColor",
    "secondary": "SystemColorButtonFaceColor", "on-secondary": "SystemColorButtonTextColor",
    "brass": "SystemColorWindowTextColor", "brass-text": "SystemColorWindowTextColor", "brass-tint": "SystemColorWindowColor",
    "success": "SystemColorWindowTextColor", "warning": "SystemColorWindowTextColor", "error": "SystemColorWindowTextColor",
    "focus": "SystemColorHighlightColor", "scrim": "SystemColorWindowColor",
    "ink": "SystemColorWindowTextColor", "staff": "SystemColorWindowTextColor",
    "uncertain": "SystemColorHotlightColor", "very-uncertain": "SystemColorHotlightColor",
    "adlib-tint": "SystemColorWindowColor", "loop-tint": "SystemColorWindowColor", "loop-edge": "SystemColorHighlightColor",
    "cursor": "SystemColorHighlightColor", "cursor-tint": "SystemColorWindowColor",
    "selection-tint": "SystemColorWindowColor", "selection-edge": "SystemColorHighlightColor",
    "model-1": "SystemColorWindowTextColor", "model-2": "SystemColorWindowTextColor",
    "model-3": "SystemColorWindowTextColor", "model-4": "SystemColorWindowTextColor",
}


def windows_theme_dictionaries(light: str, dark: str) -> list[str]:
    """The Light, Dark and HighContrast theme dictionaries of every colour role, for two modes of tokens.json."""
    rs = roles()
    X = ["    <ResourceDictionary.ThemeDictionaries>"]
    for mode, key in ((light, "Light"), (dark, "Dark")):
        X.append(f'        <ResourceDictionary x:Key="{key}">')
        for r in rs:
            a = alpha(mode, r)
            h = hexval(mode, r)[1:]
            X.append(f'            <Color x:Key="Bc{pascal(r)}Color">#{round(a * 255):02X}{h}</Color>')
        for r in rs:
            X.append(f'            <SolidColorBrush x:Key="Bc{pascal(r)}Brush" Color="{{StaticResource Bc{pascal(r)}Color}}"/>')
        X.append("        </ResourceDictionary>")
    X.append('        <ResourceDictionary x:Key="HighContrast">')
    for r in rs:
        X.append(f'            <StaticResource x:Key="Bc{pascal(r)}Color" ResourceKey="{HC_SYSTEM[r]}"/>')
    for r in rs:
        X.append(f'            <SolidColorBrush x:Key="Bc{pascal(r)}Brush" Color="{{ThemeResource {HC_SYSTEM[r]}}}"/>')
    X += ["        </ResourceDictionary>", "    </ResourceDictionary.ThemeDictionaries>"]
    return X


XAML_OPEN = ['<ResourceDictionary',
             '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
             '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">']


def windows_pink() -> str:
    """The hidden Pink palette (design/system.md §10): the colour roles only, merged after BrasscribeTheme.xaml."""
    X = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {HEADER} -->",
         "<!-- The hidden Pink palette (design/system.md §10). Merged after BrasscribeTheme.xaml while Pink is chosen, so its",
         "     colour roles win; Light and Dark follow the system. Contrast themes still map every role to the system's colours. -->"]
    X += XAML_OPEN + windows_theme_dictionaries("pink", "pink-dark") + ["</ResourceDictionary>", ""]
    return "\n".join(X)


def windows_outputs() -> dict[str, str | bytes]:
    X = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {HEADER} -->",
         "<!-- Merge into App.xaml: <ResourceDictionary Source=\"ms-appx:///Themes/BrasscribeTheme.xaml\"/>.",
         "     Use {ThemeResource BcTextBrush} etc. Contrast themes map every role to the user's system colours. -->"]
    X += XAML_OPEN + windows_theme_dictionaries("light", "dark") + [""]
    X.append("    <!-- Spacing (epx), radii, sizes -->")
    for k, v in group("space").items():
        X.append(f'    <x:Double x:Key="BcSpace{k}">{fmt(dimension(v))}</x:Double>')
        X.append(f'    <Thickness x:Key="BcPadding{k}">{fmt(dimension(v))}</Thickness>')
    for k, v in group("radius").items():
        X.append(f'    <CornerRadius x:Key="BcRadius{pascal(k)}">{fmt(dimension(v))}</CornerRadius>')
    X.append(f'    <x:Double x:Key="BcTouchMin">{fmt(dimension(TOKENS["size"]["touch-min-windows"]))}</x:Double>')
    X.append(f'    <x:Double x:Key="BcContentMaxWidth">{fmt(dimension(TOKENS["size"]["content-max"]))}</x:Double>')
    X.append(f'    <x:Double x:Key="BcSidebarWidth">{fmt(dimension(TOKENS["size"]["sidebar"]))}</x:Double>')
    for k in ("cursor-width", "focus-width", "focus-gap", "loop-edge-width", "selection-edge-width"):
        X.append(f'    <x:Double x:Key="BcScore{pascal(k)}">{fmt(dimension(TOKENS["score"][k]))}</x:Double>')
    X += ["", "    <!-- Motion (ms); check UISettings.AnimationsEnabled and fall back to BcDurationReduced cross-fades -->"]
    for k, v in TOKENS["motion"]["duration"].items():
        X.append(f'    <x:Double x:Key="BcDuration{pascal(k)}">{v["$value"]["value"]}</x:Double>')
    X += ["", "    <!-- Type ramp: each style is based on the WinUI ramp style it maps to -->",
          '    <FontFamily x:Key="BcDisplayFontFamily">ms-appx:///Assets/Fonts/InstrumentSerif-Regular.ttf#Instrument Serif</FontFamily>']
    weight = {400: "Normal", 500: "Medium", 600: "SemiBold", 700: "Bold"}
    for k, v in group("typography").items():
        plat = v.get("$extensions", {}).get("no.brasscribe.platform")
        if not plat:
            continue
        w = plat["windows"]
        X.append(f'    <Style x:Key="Bc{pascal(k)}TextBlockStyle" TargetType="TextBlock" BasedOn="{{StaticResource {w["style"]}TextBlockStyle}}">')
        if "display" in v["$value"]["fontFamily"]:
            X.append('        <Setter Property="FontFamily" Value="{StaticResource BcDisplayFontFamily}"/>')
        X.append(f'        <Setter Property="FontWeight" Value="{weight[v["$value"]["fontWeight"]]}"/>')
        X.append(f'        <Setter Property="FontSize" Value="{fmt(w["sizeEpx"])}"/>')
        X.append(f'        <Setter Property="LineHeight" Value="{fmt(w["lineHeightEpx"])}"/>')
        X.append('        <Setter Property="TextWrapping" Value="Wrap"/>')
        X.append("    </Style>")
    X += ["", "    <!-- Icons: Segoe Fluent Icons glyphs for FontIcon.Glyph; custom glyphs as 20 epx path data for PathIcon -->"]
    for a in ICONS:
        kind, v = icon_source(a, "windows")
        if kind == "system":
            X.append(f'    <x:String x:Key="BcIcon{pascal(a)}">&#x{v["glyph"]};</x:String>')
        else:
            X.append(f'    <x:String x:Key="BcIconPath{pascal(a)}">{transform_path(v, 20 / 960, 0, 20)}</x:String>')
    X += ["</ResourceDictionary>", ""]
    return {"windows/BrasscribeTheme.xaml": "\n".join(X),
            "windows/BrasscribePinkTheme.xaml": windows_pink(),
            "windows/Assets/Fonts/InstrumentSerif-Regular.ttf": (BRAND / "fonts" / "InstrumentSerif-Regular.ttf").read_bytes(),
            "windows/Assets/Fonts/OFL.txt": (BRAND / "fonts" / "OFL.txt").read_bytes()}


# ---------------------------------------------------------------- Web (Studio)

FORCED = {  # role -> CSS system colour under forced-colors
    "bg": "Canvas", "surface": "Canvas", "surface-raised": "Canvas", "text": "CanvasText", "text-muted": "CanvasText",
    "border": "CanvasText", "border-strong": "CanvasText", "primary": "Highlight", "on-primary": "HighlightText",
    "secondary": "ButtonFace", "on-secondary": "ButtonText", "brass": "CanvasText", "brass-text": "CanvasText",
    "brass-tint": "Canvas", "success": "CanvasText", "warning": "CanvasText", "error": "CanvasText", "focus": "Highlight",
    "scrim": "Canvas", "ink": "CanvasText", "staff": "CanvasText", "uncertain": "LinkText", "very-uncertain": "LinkText",
    "adlib-tint": "Canvas", "loop-tint": "Canvas", "loop-edge": "Highlight", "cursor": "Highlight", "cursor-tint": "Canvas",
    "selection-tint": "Canvas", "selection-edge": "Highlight",
    "model-1": "CanvasText", "model-2": "CanvasText", "model-3": "CanvasText", "model-4": "CanvasText",
}


def css_color(mode: str, r: str) -> str:
    a = alpha(mode, r)
    h = hexval(mode, r)
    return h if a == 1 else f"rgb({int(h[1:3], 16)} {int(h[3:5], 16)} {int(h[5:7], 16)} / {fmt(a)})"


def web_outputs() -> dict[str, str | bytes]:
    rs = roles()

    def block(mode: str, indent: str) -> list[str]:
        return [f"{indent}--bc-{r}: {css_color(mode, r)};" for r in rs]

    C = [f"/* {HEADER} */", "/* Import fonts.css too if the page uses the display face. */", "",
         ":root {", "  color-scheme: light;"]
    C += block("light", "  ")
    fam = TOKENS["font"]["family"]
    quote = lambda xs: ", ".join(f'"{x}"' if " " in x else x for x in xs)
    C += [f"  --bc-font-text: {quote(['system-ui', '-apple-system', 'Segoe UI Variable Text', 'Segoe UI', 'Roboto', 'sans-serif'])};",
          f"  --bc-font-display: {quote(fam['display']['$value'])};",
          f"  --bc-font-mono: {quote(['ui-monospace', 'SF Mono', 'Cascadia Mono', 'Roboto Mono', 'Menlo', 'monospace'])};"]
    for k, v in group("typography").items():
        val = v["$value"]
        C.append(f"  --bc-type-{k}-size: {fmt(val['fontSize']['value'] / 16)}rem;")
        C.append(f"  --bc-type-{k}-line: {fmt(val['lineHeight'])};")
        C.append(f"  --bc-type-{k}-weight: {val['fontWeight']};")
    for k, v in group("space").items():
        C.append(f"  --bc-space-{k}: {fmt(dimension(v) / 16)}rem;")
    for k, v in group("radius").items():
        C.append(f"  --bc-radius-{k}: {fmt(dimension(v))}px;")
    for k, v in TOKENS["elevation"].items():
        if k.startswith("$"):
            continue
        sh = v["$value"]
        def shadow_color(c: dict) -> str:
            h = c["hex"]
            return f"rgb({int(h[1:3], 16)} {int(h[3:5], 16)} {int(h[5:7], 16)} / {fmt(c.get('alpha', 1))})"
        val = "none" if not sh else ", ".join(
            f"{fmt(s['offsetX']['value'])}px {fmt(s['offsetY']['value'])}px {fmt(s['blur']['value'])}px {fmt(s['spread']['value'])}px {shadow_color(s['color'])}" for s in sh)
        C.append(f"  --bc-elevation-{k}: {val};")
    for k, v in TOKENS["motion"]["duration"].items():
        C.append(f"  --bc-duration-{k}: {v['$value']['value']}ms;")
    for k, v in TOKENS["motion"]["easing"].items():
        C.append(f"  --bc-ease-{k}: cubic-bezier({', '.join(fmt(x) for x in v['$value'])});")
    for k in ("cursor-width", "focus-width", "focus-gap", "loop-edge-width", "selection-edge-width"):
        C.append(f"  --bc-score-{k}: {fmt(dimension(TOKENS['score'][k]))}px;")
    C.append(f"  --bc-touch-min: {fmt(dimension(TOKENS['size']['touch-min-web']) / 16)}rem;")
    C.append(f"  --bc-control-min: {fmt(dimension(TOKENS['size']['control-min-web']) / 16)}rem;")
    C.append(f"  --bc-target-gap: {fmt(dimension(TOKENS['size']['target-gap-web']) / 16)}rem;")
    C.append(f"  --bc-content-max: {fmt(dimension(TOKENS['size']['content-max']) / 16)}rem;")
    C += ["}", "",
          "/* Dark: follow the system unless the page pins a theme with data-theme. */",
          "@media (prefers-color-scheme: dark) {", '  :root:not([data-theme="light"]) {', "    color-scheme: dark;"]
    C += block("dark", "    ")
    C += ["    --bc-elevation-1: none;", "    --bc-elevation-2: 0 4px 16px rgb(0 0 0 / 0.5);", "    --bc-elevation-3: 0 12px 32px rgb(0 0 0 / 0.6);",
          "  }", "}", ':root[data-theme="dark"] {', "  color-scheme: dark;"]
    C += block("dark", "  ")
    C += ["  --bc-elevation-1: none;", "  --bc-elevation-2: 0 4px 16px rgb(0 0 0 / 0.5);", "  --bc-elevation-3: 0 12px 32px rgb(0 0 0 / 0.6);", "}", "",
          "/* Pink, the hidden palette (design/system.md §10): data-palette=\"pink\" on the root. Light or dark",
          "   follows data-theme when the page pins one, else the system. More contrast and forced colours win. */",
          "@media (forced-colors: none) and (not (prefers-contrast: more)) {",
          '  :root[data-palette="pink"] {', "    color-scheme: light;"]
    C += block("pink", "    ")
    C += ["  }", '  :root[data-palette="pink"][data-theme="dark"] {', "    color-scheme: dark;"]
    C += block("pink-dark", "    ")
    C += ["  }", "}",
          "@media (forced-colors: none) and (not (prefers-contrast: more)) and (prefers-color-scheme: dark) {",
          '  :root[data-palette="pink"]:not([data-theme="light"]) {', "    color-scheme: dark;"]
    C += block("pink-dark", "    ")
    C += ["  }", "}", "",
          "/* High contrast: our palettes when the user asks for more contrast; tints become outlines.",
          "   Light or dark follows the resolved theme: data-theme when the page pins one, else the system.",
          "   Under forced colours the system colours below win instead. */"]
    more = "@media (prefers-contrast: more) and (forced-colors: none)"
    no_shadow = ["--bc-elevation-1: none;", "--bc-elevation-2: none;", "--bc-elevation-3: none;"]

    def hc(selector: str, mode: str, media: str | None) -> list[str]:
        scheme = "light" if mode == "high-contrast-light" else "dark"
        ind = "    " if media else "  "
        body = [f"{ind[:-2]}{selector} {{", f"{ind}color-scheme: {scheme};", *block(mode, ind), *(ind + s for s in no_shadow), f"{ind[:-2]}}}"]
        return [f"{media} {{", *body, "}"] if media else body

    C += hc(':root:not([data-theme="dark"])', "high-contrast-light", more)
    C += hc(':root:not([data-theme="light"])', "high-contrast", f"{more} and (prefers-color-scheme: dark)")
    C += hc(':root[data-theme="dark"]', "high-contrast", more)
    C += hc(':root[data-theme="high-contrast"]', "high-contrast", None)
    C += hc(':root[data-theme="high-contrast-light"]', "high-contrast-light", None)
    C += ["",
          "/* Forced colours (Windows contrast themes): system colours only; shape carries the meaning. */",
          "@media (forced-colors: active) {", "  :root {"]
    C += [f"    --bc-{r}: {FORCED[r]};" for r in rs]
    C += ["    --bc-elevation-1: none;", "    --bc-elevation-2: none;", "    --bc-elevation-3: none;", "  }", "}", "",
          "/* Reduced motion: no movement; state changes cross-fade at most --bc-duration-reduced. */",
          "@media (prefers-reduced-motion: reduce) {", "  :root {",
          "    --bc-duration-fast: 0ms;", "    --bc-duration-base: var(--bc-duration-reduced);", "    --bc-duration-slow: var(--bc-duration-reduced);",
          "  }", "}", ""]

    F = [f"/* {HEADER} */", "/* Instrument Serif, SIL Open Font License 1.1 (fonts/OFL.txt). Display sizes (28px and up) only. */",
         "@font-face {", '  font-family: "Instrument Serif";', '  src: url("fonts/InstrumentSerif-Regular.ttf") format("truetype");',
         "  font-weight: 400;", "  font-style: normal;", "  font-display: swap;", "}",
         "@font-face {", '  font-family: "Instrument Serif";', '  src: url("fonts/InstrumentSerif-Italic.ttf") format("truetype");',
         "  font-weight: 400;", "  font-style: italic;", "  font-display: swap;", "}", ""]

    compat = {"bg": "bg", "surface": "surface", "text": "text", "text-muted": "text-muted", "ink": "ink", "staff": "staff",
              "uncertain": "uncertain", "very-uncertain": "very-uncertain", "adlib-tint": "adlib-tint", "loop-tint": "loop-tint",
              "loop-edge": "loop-edge", "cursor": "cursor", "focus": "focus", "error": "error", "ok": "success",
              "border": "border-strong", "m1": "model-1", "m2": "model-2", "m3": "model-3", "m4": "model-4"}
    S = [f"/* {HEADER} */", "/* Maps the variable names in studio/src/styles.css onto the Brasscribe tokens.",
         "   Load after brasscribe.css and instead of Studio's own colour blocks. */", ":root {"]
    S += [f"  --{k}: var(--bc-{v});" for k, v in compat.items()]
    S += ["  --space: var(--bc-space-4);", "  font-family: var(--bc-font-text);", "}", ""]

    out: dict[str, str | bytes] = {"web/brasscribe.css": "\n".join(C), "web/fonts.css": "\n".join(F), "web/studio-compat.css": "\n".join(S)}
    for f in ("InstrumentSerif-Regular.ttf", "InstrumentSerif-Italic.ttf", "OFL.txt"):
        out[f"web/fonts/{f}"] = (BRAND / "fonts" / f).read_bytes()
    js = [f"// {HEADER}", "// Path data on the Material Symbols 960 grid (viewBox \"0 -960 960 960\"), keyed by action.",
          "globalThis.BrasscribeIcons = {"]
    for a in ICONS:
        js.append(f'  "{a}": "{icon_source(a, "material")[1]}",')
    js += ["};", ""]
    out["web/icons.js"] = "\n".join(js)
    for a in ICONS:
        _, d = icon_source(a, "material")
        out[f"web/icons/{a}.svg"] = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" width="24" height="24" '
                                     f'fill="currentColor" aria-hidden="true"><path d="{d}"/></svg>\n')
    return out


# ---------------------------------------------------------------- icon map (docs)

def icon_map() -> str:
    L = [f"<!-- {HEADER} -->", "# Icon map", "",
         "One icon per action on every platform. The label is always shown (or is the accessible name in the transport row).",
         "Custom glyphs live in `design/brand/icons/custom/`.", "",
         "| Action | English | Norsk (bokmål) | Apple (SF Symbols) | Android and Studio (Material Symbols Rounded) | Windows (Segoe Fluent Icons) |",
         "|---|---|---|---|---|---|"]
    for a, v in ICONS.items():
        m = v["material"]
        m = f"`{m}`" if isinstance(m, str) else f"custom `{m['custom']}`"
        w = v["windows"]
        w = f"`{w['name']}` U+{w['glyph']}" if "glyph" in w else f"custom `{w['custom']}` (PathIcon)"
        L.append(f"| {a} | {v['en']} | {v['nb']} | `{v['apple']}` | {m} | {w} |")
    L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------- main

def outputs() -> dict[Path, str | bytes]:
    out: dict[Path, str | bytes] = {}
    for fn in (apple_outputs, android_outputs, windows_outputs, web_outputs):
        for rel, content in fn().items():
            out[DIST / rel] = content
    out[DIST / "icon-map.md"] = icon_map()
    out[ROOT / "docs" / "accessibility" / "design-tokens.json"] = a11y_json()
    return out


def as_bytes(c: str | bytes) -> bytes:
    return c.encode() if isinstance(c, str) else c


GENERATED_DIRS = ("apple/BrasscribeDesign.xcassets", "android/kotlin", "android/res/drawable", "web/icons")


def stale() -> list[str]:
    want = outputs()
    bad = [str(p.relative_to(ROOT)) for p, c in want.items() if not p.exists() or p.read_bytes() != as_bytes(c)]
    for d in GENERATED_DIRS:
        base = DIST / d
        if base.exists():
            for f in base.rglob("*"):
                if f.is_file() and f not in want and not f.name.startswith("ic_launcher"):
                    bad.append(str(f.relative_to(ROOT)) + " (not generated any more)")
    return sorted(bad)


def write() -> None:
    want = outputs()
    for d in GENERATED_DIRS:
        base = DIST / d
        if base.exists():
            for f in base.rglob("*"):
                if f.is_file() and f not in want and not f.name.startswith("ic_launcher"):
                    f.unlink()
    for p, c in want.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(as_bytes(c))
    print(f"wrote {len(want)} files")


def main(argv: list[str]) -> int:
    if argv[:1] == ["--check"]:
        bad = stale()
        if bad:
            print("Design outputs are out of date. Run `uv run design/tokens/build.py`:")
            print("\n".join("  " + b for b in bad))
            return 1
        print("design outputs are in sync")
        return 0
    write()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
